### PR TITLE
Allow tasty-expected-failure 0.12

### PR DESCRIPTION
**Pull request by sjakobi**
Context: https://github.com/commercialhaskell/stackage/issues/5537

### CODE REVIEW

**Comment by sjakobi** [comment]
I have run the relevant test suites locally with the new version.

**Comment by sjakobi** [comment]
> Will be worth updating our nix derivation package? Currently, it's pinned on `0.11.1.1`
> 
> EDIT: My rationale is to keep our dependencies as most up to date as we can

Yeah, we could, although I haven't seen any changes that we'd obviously profit from.

Actually I'm not sure why we don't bump the nix dependencies more often. Maybe it's about avoiding churn in the build cache?

**Comment by german1608** [comment]
> Actually I'm not sure why we don't bump the nix dependencies more often. Maybe it's about avoiding churn in the build cache?

That might be the reason.

Let's keep the nix derivation as it is, if we _need_ to update it they we'll do it.

**Comment by Gabriel439** [comment]
I published the matching revisions to Hackage

**Pull request merged**
