### PR TITLE
Add wildcard support in merge

### PR DESCRIPTION
**Pull request by TristanCacqueray**
Related https://github.com/dhall-lang/dhall-lang/issues/961

### CODE REVIEW

**Comment by Gabriel439** [comment]
@TristanCacqueray: Note that this needs to be standarized first before we can update the Haskell implementation, but I might be able to help with that soon

**Comment by Gabriel439** [comment]
@TristanCacqueray: Whoops, I completely missed that you are already working on a pull request to standardize this, too.  Ignore me 🙂

**Comment by TristanCacqueray** [comment]
I probably broke many laws in the proposed standard and implementation changes... Those PRs likely need a lot of help as I am not familiar with the languages, and if you don't mind, I'd be happy to help and contribute that feature.

**Comment by TristanCacqueray** [comment]
Actually this doesn't type check as expected: 

```
dhall <<< 'merge { Red = 42, _ = True } < Red | Green | Blue >.Red'
42
```

**Comment by Gabriel439** [comment]
I will close this for now since the corresponding standard proposal stalled

**Pull request closed without merging**
