### PR TITLE
Update dhall-lang to latest master

### PR DESCRIPTION
**Pull request by sjakobi**
Disables a currently failing testcase.

### CODE REVIEW

**Comment by sjakobi** [comment]
I really think this is a GitHub bug. It seems that, when you clone a repo or fetch it as a submodule, GitHub doesn't include commits that aren't part of a branch. That means https://github.com/dhall-lang/dhall-lang/commit/57909f811bccf401b17ac90314c6c1fcec074c53 became unavailable once the branch for https://github.com/dhall-lang/dhall-lang/pull/669, was deleted.

**Comment by sjakobi** [comment]
More likely: I misunderstood how `git clone` works: Apparently only commits that are reachable from a reference (like a branch) are included.

[The `--remote` option](https://git-scm.com/docs/git-submodule#git-submodule---remote) seems useful though: If I run `git submodule update --init --remote` from the current `master`, it checks out https://github.com/dhall-lang/dhall-lang/commit/1ed98c33ce5078161109885f0b16b3828958f4e2, which is the reachable commit that includes https://github.com/dhall-lang/dhall-lang/commit/57909f811bccf401b17ac90314c6c1fcec074c53.

It seems like we'll need to make sure that the `dhall-lang` submodule points to a (permanently) reachable commit before merging a PR.

**Comment by sjakobi** [comment]
Not sure what's going on with Hydra here: https://hydra.dhall-lang.org/jobset/dhall-haskell/1200#tabs-errors

**Comment by Gabriel439** [comment]
@sjakobi: `dhall.cabal` needs to be fixed to replace `dhall-lang/tests/normalization/success/prelude/package.dhall` with `tests/typecheck/success/prelude*.dhall`.  I fixed the location of that test on my `dhall-lang` branch but forgot to update the Haskell branch with the matching change

**Comment by sjakobi** [comment]
If tried to reproduce the issue of missing Dhall files locally, by producing an sdist, unpacking it, and executing

    cabal run -- dhall:dhall --file dhall-1.25.0/dhall-lang/Prelude/package.dhall

This unexpectedly succeeded, even though parts of the Prelude were not included in the tarball! Only once I deleted `~/.cache/{dhall,dhall-haskell}`, the command failed. Does `dhall` work as expected when it can import e.g. `./XML/package.dhall sha256:6aed7e845c29bc528ced19b99f860c5bcd50f24a1394631fe66f751999f85361` even though that file doesn't exist?

**Comment by sjakobi** [comment]
I'm merging this to fix `master`.

**Comment by Gabriel439** [comment]
@sjakobi: Yes, `dhall` can import a file purely by hash if it is in the cache.  For example `missing sha256:6aed7e845c29bc528ced19b99f860c5bcd50f24a1394631fe66f751999f85361` can succeed in this way

**Comment by sjakobi** [comment]
Maybe there should be something like a `--no-cache` mode that can check whether the imports actually exist (and whether the sha256 hashes are still correct)!?

**Comment by Gabriel439** [comment]
@sjakobi: You can get something pretty close by doing `XDG_CACHE_HOME=/var/empty dhall ...`

**Pull request merged**
