### PR TITLE
dhall: raise upper bound on Diff

### PR DESCRIPTION
**Pull request by JackKelly-Bellroy**
We have set `allow-newer` internally and it is working.

### CODE REVIEW

**Comment by JackKelly-Bellroy** [comment]
CI failure appears unrelated.

**Comment by winitzki** [comment]
Currently the macos build seems to be broken. I've been trying randomly poking around to fix it but I don't really know what I'm doing in this build system. https://github.com/dhall-lang/dhall-haskell/pull/2586  Anyone has any ideas? The failure is around `libsodium` and has to do with macos architectures (x86 vs arm).

**Comment by mmhat** [comment]
@JackKelly-Bellroy Thank you!

**Comment by ysangkok** [comment]
@Gabriella439 Would it be possible to get this bump as a Hackage revision? Then we could get Dhall back into Stackage.

**Comment by kokobd** [comment]
We are also waiting for a Hackage revision so `allow-newer` can be removed from our `cabal.project`

**Comment by Gabriella439** [comment]
I published a matching revision

**Pull request merged**
