### PR TITLE
Use `DeriveLift` instead of GHC Generics to derive `Lift`

### PR DESCRIPTION
**Pull request by Gabriel439**
See: https://github.com/dhall-lang/dhall-haskell/issues/1639#issuecomment-576692324

### CODE REVIEW

**Comment by sjakobi** [comment]
Apparently GHC 7.10 doesn't support `DeriveLift`… :/

At this point we could probably apply a bit of CPP, or wait and see whether https://gitlab.haskell.org/ghc/ghc/issues/17723 might get fixed in time for `dhall` to support GHC 8.10…

**Comment by sjakobi** [comment]
> At this point we could probably apply a bit of CPP, or wait and see whether https://gitlab.haskell.org/ghc/ghc/issues/17723 might get fixed in time for `dhall` to support GHC 8.10…

Ryan Scott came to the rescue again and suggested a few more possibilities to avoid the panic! :)

https://gitlab.haskell.org/ghc/ghc/issues/17722#note_248493

**Comment by jvanbruegge** [comment]
Is GHC 7 still worth supporting? Eta is dead

**Comment by Gabriel439** [comment]
I'll drop support for GHC 7.10.3, then.  My reasoning is that if Eta cannot upgrade to support GHC 8.0 then it probably is dead.  They will still be able to build against older versions of `dhall` in the meantime

**Comment by jvanbruegge** [comment]
In general, I think a three to four version supoort window would be healthy. E.g. `8.10`, `8.8` `8.6` and `8.4`

**Comment by Gabriel439** [comment]
@jvanbruegge: It usually comes down to the cost of supporting old versions, which is usually one of the following two factors:

* The time it takes CI to build with that GHC version (usually slower for older versions)
* The maintenance costs of not being able to use new GHC features

So usually I only drop older versions if one of those two become prohibitive.

Note that CI does not build all of the GHC versions in between.  We only build the oldest, newest, and possibly one version behind newest (if the newest is still buggy), and assume that all versions in between are also supported.

**Comment by jvanbruegge** [comment]
Yeah of course, no point in dropping support if it is not needed. I just meant in case of engineering benefits like this, a four version window should be the one to strike for

**Pull request merged**
