### PR TITLE
Add null check

### PR DESCRIPTION
**Pull request by jneira**
As it is used at least by dhall-to-cabal...

### CODE REVIEW

**Comment by quasicomputational** [comment]
`Data.Foldable.null` ought to be good enough, I think? Even if there's an asymptotic win, we should just over-ride the default `Foldable` implementation and use that in client code (i.e., in `dhall-to-cabal`).

**Comment by Gabriel439** [comment]
@quasicomputational: Yeah, `Data.Foldable.null` should do the right thing in this case

**Comment by Gabriel439** [comment]
I also have a branch out that builds against the `Dhall.Map` changes: https://github.com/dhall-lang/dhall-to-cabal/compare/gabriel/latest_dhall

**Comment by jneira** [comment]
Thanks for pointing it out, closing this

**Pull request closed without merging**
