### PR TITLE
Version 1.26.1 → 1.27.0

### PR DESCRIPTION
**Pull request by Gabriel439**

### CODE REVIEW

**Comment by jneira** [comment]
Could we add #1320 to the list of fixes? windows users out there will be a little happier 😄 
Or it had to be added in the `1.26.1` release?

**Comment by Gabriel439** [comment]
@sjakobi: I plan to do something like this:

https://opensource.stackexchange.com/a/2695

Specifically:

* Keep BSD3 as the license specified in the `dhall-json.cabal` file
* Specify multiple `license-files` in `dhall-json.cabal`, one for each license specifying which files the license applies to

**Comment by Gabriel439** [comment]
@jneira: Those were release as part of 1.26.1, but I can update that earlier changelog, too

**Comment by sjakobi** [comment]
The two licenses for `dhall-json` LGTM! It would be good to mention this in the changelog IMHO.

**Comment by Gabriel439** [comment]
Alright, I will cut the release tomorrow morning if nobody objects.  I don't plan to wait for https://github.com/dhall-lang/dhall-haskell/pull/1443 since that looks like it's a more risky change than I originally thought.

**Pull request merged**
