### PR TITLE
RFC: A custom data structure for list literals

### PR DESCRIPTION
**Pull request by sjakobi**
On a whim I have implemented [a data structure](https://github.com/sjakobi/dhall-list/blob/master/src/DhallList/Internal.hs) that is optimized for the built-in list operations: `head`, `last`, concatenation, `length`, `reverse` are all O(1).

In "normal" form, a  `DhallList` of at least 4 elements is a pretty thin wrapper around a `Vector`, which makes it more memory efficient than the `Seq` type that we currently use.

I have to admit that I haven't seen many performance benefits so far – in synthetic list-heavy benchmarks, it's a bit faster. There's still quite a bit of room for improvement though, mostly in folds, traversals and `toList` conversion.

I've opened this PR mostly to see whether there's any interest in using `DhallList` (in which case the code could be moved into the `dhall` package). I won't be disappointed if there's none – it was fun experiment anyway! :)

### CODE REVIEW

**Comment by Gabriel439** [comment]
@sjakobi: The main issue with using a `Vector` instead of a `Sequence` is that something like `Prelude.List.map` will become O(N^2) due to repeatedly prepending one element to the `List`

**Comment by sjakobi** [comment]
That's why I qualified that sentence with

> In "normal" form

…although I should have expanded on what I mean by that. Operations like consing and concatenation are supported via other "non-normalizing" constructors on the `Inner` type:

```haskell
data Inner a
  = IEmpty
  | IOne a -- TODO: Consider removing this constructor
  | ICons {-# unpack #-} !Int a !(Inner a)
    -- ^ Invariant: length >= 2
  | ISnoc {-# unpack #-} !Int !(Inner a) a
    -- ^ Invariant: length >= 2
  | IVec {-# unpack #-} !(Vector a)
    -- ^ Invariant: length >= 2
  | IRev {-# unpack #-} !Int !(Inner a)
    -- ^ Invariant: length >= 2
    --   Invariant: The inner Inner is not an IRev itself
  | ICat {-# unpack #-} !Int !(Inner a) !(Inner a)
    -- ^ Invariant: both inner Inners have length >= 2
```

The "outer" data structure ensures that access to the first and last element is O(1):

```haskell
data DhallList a
  = Empty
  | One a
  | Many a !(Inner a) a
```

Operations like `map` or `traverse` normalize / canonicalize an `Inner`, removing any `ICons`, `ISnoc`, `IRev` or `ICat` constructor in favour of `IVec`. Subsequent operations are faster since they can use the optimized `Vector` implementations.

**Comment by Gabriel439** [comment]
@sjakobi: At that point you've essentially reimplemented `Data.Sequence`.  See the underlying `FingerTree` type: http://hackage.haskell.org/package/containers-0.6.2.1/docs/src/Data.Sequence.Internal.html#FingerTree

**Comment by sjakobi** [comment]
Hmm, I don't really see the similarity. `DhallList` doesn't require any bookkeeping or rebalancing. Apart from traversals, everything is truly O(1) – concatenation of `Seq`s is O(log(min(n1,n2))) OTOH, even consing is only amortized O(1) because it triggers rebalancing.

**Comment by sjakobi** [comment]
This is why `Seq` needs to be more complicated than `DhallList` BTW:

> * Logarithmic-time splitting with splitAt, take and drop
> * Logarithmic-time access to any element with lookup, !?, index, insertAt, deleteAt, adjust', and update

`dhall` uses none of this!

**Comment by Gabriel439** [comment]
@sjakobi: I still don't think it's wise for us to maintain our own `Seq`-like data structure until we have benchmarks showing that `List` operations are the bottleneck.  `Seq` is based on peer-reviewed publications with proven time complexity bounds (in Haskell no less, which is impressive when you factor in the difficulty of reasoning about time complexity in a lazy language), has been optimized with careful benchmarking and (most importantly!) is maintained by somebody else.

For example, I'm not convinced that concatenation is truly O(1).  From looking at the implementation it looks like concatenation is only deferring work to `itolist`.  In the general case of concatenating two large `DhallList`s it invokes `iglue` which emits an `ICat` constructor which `itolist` transforms into `++` for Haskell lists, which is O(N).

**Comment by sjakobi** [comment]
Indeed `itoList` is currently suboptimal. I plan on changing it to write to a mutable vector instead.

I fully agree that there's no point in adopting `DhallList` unless we know that it's better and there's a real need.

@fizruk, you had reported problems with list performance in https://github.com/dhall-lang/dhall-lang/issues/552#issuecomment-513885405 – do these issues persist or have you been able to resolve them in some way?

**Comment by fizruk** [comment]
@sjakobi we still have a Dhall files that take seconds to load, so optimizations are welcome 😊 we are doing normalization occasionally when time gets too big, so it is not urgent for us. We are using Dhall 1.24.0 and I just checked that Dhall 1.27.0 is slightly faster (maybe takes 20% less time), but the load time is still noticeable.

**Comment by sjakobi** [comment]
Thanks for the quick response @fizruk! :)

There are some improvements that I want to implement in `dhall-list`. Once that's done, would you mind giving my branch a try on your code?

**Comment by fizruk** [comment]
@sjakobi sure, ping me when there is something to try out 😊

**Comment by sjakobi** [comment]
I've somewhat lost my steam after getting some but not very exciting performance improvements, so I'll record my current thoughts:

* `DList` or `VectorBuilder` might make nice replacements for the `Inner` type in `DhallList` – both offer fast O(1) concatenation.

* I've read about "catenable deques" which in my understanding should be a pretty good fit for Dhall's `List`: [1](https://stackoverflow.com/questions/16422795/where-is-the-simpler-real-time-catenable-deque-work-of-tarjan-and-mihaescu), [2](https://www.guillaumesalvan.com/en/post/catenabledeque/).  I can't make much sense of it though and suspect that they have similarly high constants as `Data.Sequence`.

---

@fizruk I'm still interested in figuring out why your code is slow and what we can do to speed it up. Could you possibly profile it? There are some profiling instructions in the [README](https://github.com/dhall-lang/dhall-haskell#profiling).

**Pull request closed without merging**
