### PR TITLE
Implement importing `as Location`

### PR DESCRIPTION
**Pull request by f-f**
..as standardized in https://github.com/dhall-lang/dhall-lang/pull/585

### CODE REVIEW

**Comment by f-f** [comment]
This will need to wait for:
- https://github.com/dhall-lang/dhall-lang/pull/605
- a fix to make the test introduced in https://github.com/dhall-lang/dhall-lang/pull/587 pass

**Comment by Gabriel439** [comment]
@f-f: Note that you can skip the latter test if necessary.  I can always fix it in a subsequent pull request

**Comment by f-f** [comment]
@Gabriel439 I think it's fine to wait for that test to be fixed because we'd need a new release for using this in Spago anyways

I looked into that failure, and it looks like the parser here is trying to parse the "nested" import (after `using`) as a type annotation. This is the new - correct - encoding (in CBOR's diag syntax):
```
[24, h'1220B0E3EC1797B32C80C0BCB7E8254B08C7E9E35E75E6B410C7AC21477AB90167AD', 0, 1, [24, h'122016173E984D35EE3FFD8B6B79167DF89480E67D1CD03EA5D0FC93689E4D928E61', 0, 3, "a.dhall"], "raw.githubusercontent.com", "dhall-lang", "Prelude", "c79c2bc3c46f129cc5b6d594ce298a381bcae92c", "List", "replicate", null]
```

But this is how we parse it:
```
[24, null, 0, 1, [26, [0, [24, h'122016173E984D35EE3FFD8B6B79167DF89480E67D1CD03EA5D0FC93689E4D928E61', 0, 3, "a.dhall"], ["sha256", 0]], ["b0e3ec1797b32c80c0bcb7e8254b08c7e9e35e75e6b410c7ac21477ab90167ad", 0]], "raw.githubusercontent.com", "dhall-lang", "Prelude", "c79c2bc3c46f129cc5b6d594ce298a381bcae92c", "List", "replicate", null]
--                     ^ function application
--                ^ type annotation
```

**Comment by f-f** [comment]
@Gabriel439 thanks! 🙂

**Comment by Gabriel439** [comment]
@f-f: You're welcome! 🙂

**Pull request merged**
