### PR TITLE
dhall format: Strip trailing whitespace

### LINKED ISSUE #183: dhall-format inserts trailing whitespace
Given consecutive indented (ie. non-top-level) `let` blocks, `dhall-format` inserts trailing whitespace.

Example:
```
    let foo = 1

in    λ(bar : Integer)
    →     let exposePort =
                  λ(portSpec : { ext : Integer, int : Integer })
                → Integer/show portSpec.ext ++ ":" ++ Integer/show portSpec.int
      
      in  let exposeSamePort =
                λ(port : Integer) → exposePort { ext = port, int = port }
      
      in  { blah = bar }
```

Here, whitespace is inserted on the empty lines above the last two lines which begin with `in`.

### PR DESCRIPTION
**Pull request by ocharles**
This uses Data.Text.Prettyprint.Doc.removeTrailingWhitespace to remove
trailing whitespace from pretty printed documents.

In the process I also refactored this module a bit to remove duplication.

Fixes #183.

### CODE REVIEW

**Comment by ocharles** [comment]
Note that this is *not* ready to be merged as it removes blank lines. Working with @quchen on seeing where the problem is.

**Comment by ocharles** [comment]
Looks like we need to wait until `hnix` supports `prettyprinter-1.3.0` now.

**Comment by ocharles** [comment]
Ok, if you're happy with that I'll jailbreak :+1:

**Comment by quchen** [comment]
I thought about which version to bump, but the `Pretty [a]` instance does observably change output, so tests like [tasty-golden](http://hackage.haskell.org/package/tasty-golden) are in danger of breaking.

**Comment by Gabriel439** [comment]
@quchen: Don't worry about it 🙂

**Comment by Gabriel439** [comment]
@ocharles: If you merge https://github.com/ocharles/dhall-haskell/pull/3 into your branch it should at least fix the Nix build failures

**Comment by Gabriel439** [comment]
Actually, I noticed something odd while using this branch for unrelated reasons.  It appears to mess up formatting and color codes.

For example, on `master`, the following expression:

```dhall
{ aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = 1, bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = 2, cccccccccccccccccccccccccccccccccc = 3 }
```

... is formatted as:

```dhall
{ aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa =
    1
, bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb =
    2
, cccccccccccccccccccccccccccccccccc =
    3
}
```

... with syntax highlighting.  But on this branch the highlighting is gone and it's formatted as:

```dhall
{ aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa =
1
, bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb =
2
, cccccccccccccccccccccccccccccccccc =
3
}
```

You'll see similar behavior for unions, too.

**Comment by sjakobi** [comment]
I've started working on a patch that will supersede this PR.

**Comment by sjakobi** [comment]
@Gabriel439 The missing colors are probably due to the `unAnnotateS` in `prettyExprSource`.

The removal of leading whitespace seems to be bug in a prettyprinter: See https://github.com/quchen/prettyprinter/issues/84.

**Comment by sjakobi** [comment]
Closing in favour of #1422.

**Pull request closed without merging**
