### PR TITLE
Allow pretty-simple 4.0

### PR DESCRIPTION
**Pull request by sjakobi**
http://hackage.haskell.org/package/pretty-simple-4.0.0.0/changelog

### CODE REVIEW

**Comment by sjakobi** [comment]
Note that there are some differences in the output of the `haskell-syntax-tree` command:

Old

```
$ echo 'let x : T = y in z' | dhall haskell-syntax-tree
Let
    ( Binding
        { bindingSrc0 = Nothing
        , variable = "x"
        , bindingSrc1 = Nothing
        , annotation = Just
            ( Nothing
            , Var ( V "T" 0 )
            )
        , bindingSrc2 = Nothing
        , value = Var ( V "y" 0 )
        }
    )
    ( Var ( V "z" 0 ) )
```

New:

```
Let
    ( Binding
        { bindingSrc0 = Nothing
        , variable = "x"
        , bindingSrc1 = Nothing
        , annotation = Just
            ( Nothing
            , Var
                ( V "T" 0 )
            )
        , bindingSrc2 = Nothing
        , value = Var
            ( V "y" 0 )
        }
    )
    ( Var
        ( V "z" 0 )
    )
```

Since we only use this for debugging, I think we can live without tighter bounds though.

**Review by Gabriel439 — APPROVED** [review]

**Comment by sjakobi** [comment]
I made a corresponding Hackage revision. (`hackage-cli push-cabal --incr-rev dhall/dhall.cabal`)

**Comment by Gabriel439** [comment]
@sjakobi: It looks like a flaky import test failed:

`./dhall-lang/tests/import/success/noHeaderForwardingA.dhall`

Perhaps we can use the new customizable `Manager` to extend the timeout that we use for tests

**Comment by sjakobi** [comment]
> Perhaps we can use the new customizable `Manager` to extend the timeout that we use for tests

See #2049.

**Pull request merged**
