### PR TITLE
Add `dhall-docs` to repository's README

### PR DESCRIPTION
**Pull request by german1608**
This will be the last PR as part of the GSoC project, but sure I'll keep contributing soon ;)

Let me know if I missed a place, but it looks like `dhall-docs` is fully integrated with the repository

### CODE REVIEW

**Comment by german1608** [comment]
Does it make sense to bump `dhall-docs` to `1.1.0`? Or adding another revision on `1.0.0` is enough?

---

I'd like to link to the Hackage page for `dhall-docs` in my last report for GSoC but the current revision doesn't have the latest features. @Gabriel439 or @sjakobi: Can you submit an update there, please?

**Review by sjakobi — APPROVED** [review]

**Comment by sjakobi** [comment]
If we want to make a release from `dhall-docs`' latest `master`, we have to make releases for the other packages too: https://github.com/dhall-lang/dhall-haskell/commit/8d89b441ab3477c4c4c02561679fd79b50a217ed includes changes in most of the packages.

**Comment by Gabriel439** [comment]
@german1608: Generally we bump the version number in the `.cabal` file in the pull request where we cut the release, although you can feel free to bump it earlier than that

**Comment by Gabriel439** [comment]
Also, keep in mind that we'll be cutting a new release once https://github.com/dhall-lang/dhall-lang/pull/1059 is merged

**Pull request merged**
