### PR TITLE
LSP. Fix import errors location.

### PR DESCRIPTION
**Pull request by PanAeon**
Minor clean-up (Readme and comments).
 Added tests for backend/diagnostics.

### CODE REVIEW

**Comment by Profpatsch** [comment]
Does LSP have the same merge window as the rest of dhall?

**Comment by Gabriel439** [comment]
@Profpatsch: So, the `dhall-haskell` project doesn't officially have contributing guidelines yet (it doesn't share the same guidelines as the `dhall-lang` project).  Informally, the guidelines that I've held myself to for `dhall-haskell` are a ~1-day review period before merging pull requests

**Comment by PanAeon** [comment]
I'm usually quite eager to merge everything as soon as possible. Next time I'll stick to 1 day/review rule.

**Comment by Gabriel439** [comment]
@PanAeon: No problem!  Right now it's not a huge deal, but once Frederick begins contributing more as part of Google Summer of Code then the waiting period will help people coordinate changes better

**Pull request merged**
