### PR TITLE
Build against `hnix-0.8`

### PR DESCRIPTION
**Pull request by Gabriel439**
Fixes https://github.com/dhall-lang/dhall-haskell/issues/1838

### CODE REVIEW

**Comment by Gabriel439** [comment]
I verified that `dhall-nix` still builds against the newer version of `hnix` without changes

**Comment by Anton-Latukha** [comment]
@sjakobi

Woops: I've looked at the project description, searched Reports requesting it, and opened Report that askes to add `0.8`.

Also, I think this can not look better than #1822, since it is seen you did work in there.

---

I'm also getting lost in Nix files sometimes. Moreover for that, some of Nix files in projects are manually crafted, and some are automatically generated - and often it is too obscure which are which, especially if people write Nix files without comments.

---

Sidenote: I do not know about `libsodium` situation. If `hnix-store-core-0.2` depends on unavailable in Nixpkgs `libsodium` version, that is often the case the package for separate version is explicitly created in Nixpkgs, but of course properly for `hnix-store-core-0.2` to follow upstream package versions.

Also another sidenote about `nhix-store`s: `hnix-store-remote` is `0.1.0` in Nixpkgs, and it is indeed a broken package there.

---

**Comment by Gabriel439** [comment]
@Anton-Latukha: Generally, I try to avoid deviating from the default package set as much as possible to avoid maintaining a large number of pinned dependencies, because then upgrading to newer versions of Nixpkgs becomes more difficult.  I simply locally verify that the project builds against the newer version of the dependency, which it does in this case.

The only thing I had to do in order to build locally against `hnix-0.8` (using Nix) was to add the `some` package to the package set and increase the upper bound and that was it.

Usually the only exception I make to this rule is if there is some performance improvement to using a newer version of a dependency

**Comment by Anton-Latukha** [comment]
Yes, Nixpkgs and Nix tooling could still receive some (a lot of) work, simplifications, and automation.

You know that Nixpkgs is currently objectively the best software store, technologically, as also by size, and effort put in as also the consolidation of that effort.

What I would say - we can learn from Nixpkgs mistakes.

For example, yesterday I thought: In Nixpkgs the "default" `pandoc` is old versioin `2.7.4` there, and there is a separate package `pandoc_2_9_2`. Developers stopped supporting old`2.7.4`. But people that use `pandoc` in Nixpkgs - stuck on old version, since they somehow should know there exists  `pandoc_2_9_2`, so they should manually switch to it, and then when Nixpkgs migration happens - switch back.

It should be the other way around.

Newer versions of package should be always a default tip. There no stopping the constant progress, so tip moves forward constantly.
The default tip - should always be current, if not even `master` packages. And old/stable versions should be branched-out into a separate tails, or use old package description revision, and the package manager, if the code says to it (please, `pandoc < 2.9.0`) - should prioritize finding and picking some newest `pandoc < 2.9.0` version there is in the repository automatically.

Those processes are and should be internal to the package management, and not given to manual external human work.

**Comment by Gabriel439** [comment]
@Anton-Latukha: I don't think this repository is a good forum for discussing how Nixpkgs should operate

**Comment by Anton-Latukha** [comment]
True. I would pardon the explanation, it is too late, not possible to change the core Nixpkgs processes.

**Pull request merged**
