### PR TITLE
Bumped Stack resolver to LTS 18

### PR DESCRIPTION
**Pull request by mmhat**
Also use Stack 2.7.1 in AppVeyor configuration.

### CODE REVIEW

**Review by sjakobi — APPROVED** [review]

**Comment by Gabriel439** [comment]
@mmhat: We might need to drop the Appveyor build now that we're using GitHub actions because this PR is hitting the 60 minute timeout on Appveyor

**Comment by mmhat** [comment]
@Gabriel439 We should indeed drop AppVeyor. As a remark: The timeouts yesterday were _not_ because of our compile times.
[This](https://ci.appveyor.com/project/Gabriel439/dhall-haskell/builds/39724170) build was suck in the queue for 40+ minutes and ran into the time constraint because of that.
I pushed https://github.com/dhall-lang/dhall-haskell/pull/2196/commits/1586ec9eacbbc3d37e937fe863693da93cb6b648 mainly to trigger the CI again and attended the build which started pretty quickly. After half an hour it stopped at the point indicated in the logs and it stayed that way until it ran into the time limit.

**Comment by Gabriel439** [comment]
@mmhat: I just removed AppVeyor from the set of required checks, and also stopped running AppVeyor on this project, so we'll be able to merge this now

**Comment by mmhat** [comment]
@Gabriel439 Thank you!

**Comment by Gabriel439** [comment]
You're welcome! 🙂

**Pull request merged**
