### PR TITLE
Prefer to format using record puns when possible

### PR DESCRIPTION
**Pull request by Gabriel439**
Fixes https://github.com/dhall-lang/dhall-haskell/issues/1728

### CODE REVIEW

**Comment by Gabriel439** [comment]
@sjakobi: Yeah, I wouldn't worry too much about it.  The people who are picky about how to format their code aren't going to use `dhall format` anyway.  The target audience of `dhall format` are people who just want to avoid formatting-related disagreements by having one true way to format things, so they'll tolerate an opinionated formatting tool as long as it's not egregiously bad.

**Comment by ari-becker** [comment]
> +1
> 
> I sometimes wonder what users think about `dhall format` "pushing" all the new syntactic sugar into their code bases. I'd suspect that many appreciate it and others don't… ;)

Anecdotally, we (my team and I) find that it's a really great way to find out how new language features can help improve our codebase.

The stuff that irks us about the auto-formatter isn't when it "pushes syntactic sugar", so to speak, but rather the changes to whitespace formatting that seem to happen every time we upgrade. We're starting to get to about 60,000 lines of Dhall across nearly forty repositories and every time the pretty printer changes, we get hit by enormous changesets adapting the new formatting. Obviously, we still prefer the benefits of the auto-formatter, as opinionated formatting is much more valuable, but we'd like the opinionated auto-formatter to stabilize its opinion ;)

**Comment by sjakobi** [comment]
Many thanks for the feedback @ari-becker! :)

Also, 60,000 lines sounds like _a lot_! :astonished:

**Comment by Profpatsch** [comment]
imho the built-in auto-formatter is one of the big pros of dhall over any other configuration language (looking at you nix).

**Pull request merged**
