### PR TITLE
Use Data.Map.Strict instead of Data.Map

### PR DESCRIPTION
**Pull request by phagenlocher**
When trying to read a 93Mb Dhall file with `inputExprWithSettings` (using a small list of subtitutions), Dhall currently crashes due to a spaceleak (presumably). Profiling showed that `Dhall.Map` is to blame for the allocations (with `toList` being the main retainer) and the only way to get this under control was to switch to `Data.Map.Strict`. 

Is there a specific reason why the lazy `Data.Map` is used in this module? It seems to me that laziness provides no benefit and moving to the strict version is the way to go.

Profiling eventlogs (for a smaller file) can be found here: [profiling.zip](https://github.com/user-attachments/files/17456672/profiling.zip)

### CODE REVIEW

**Comment by winitzki** [comment]
Not sure why the Hydra build failed.

**Comment by phagenlocher** [comment]
> Not sure why the Hydra build failed.

@winitzki This shouldn't be related to the code changes, right?

**Comment by winitzki** [comment]
> > Not sure why the Hydra build failed.
> 
> @winitzki This shouldn't be related to the code changes, right?

Right, I believe it has nothing to do with the code changes. All tests passed in this PR. A similar situation is happening right now in another PR: https://github.com/dhall-lang/dhall-haskell/pull/2513

Most likely it's a stale failed build that Hydra has cached for some reason. Someone needs to restart the server somewhere.

**Comment by Gabriella439** [comment]
Yeah, this is an issue with Hydra where it sometimes run out of memory.  The main reason I still use Hydra is because it ensures that the cache is preserved between builds, which at the time was hard to get with other CI solutions.  However, I have been thinking of switching to Garnix for Nix builds, which would fix this problem (I think).

**Comment by TristanCacqueray** [comment]
@Gabriella439 there is also `DeterminateSystems/magic-nix-cache-action@main` to keep the cache between GitHub actions, perhaps that would work for Dhall?

**Pull request merged**
