### PR TITLE
Fixes #1786: Moved marshalling code to own namespace

### LINKED ISSUE #1786: Move marshalling code in own module namespace
The `Dhall` module is somewhat huge and I hereby propose to split it. Since most of the code deals with marshalling I think that would be a good point to start:

- `Dhall.Marshal.Decode`
  Decoding stuff goes here
- `Dhall.Marshal.Decode.Generic`
  Generic decoding stuff goes here (`GenericFromDhall` + instances)
- `Dhall.Marshal.Decode.Instances`
  Builtin instances for decoding go here
- `Dhall.Marshal.Encode`
  Encoding stuff goes here
- `Dhall.Marshal.Encode.Generic`
  Generic encoding stuff goes here (`GenericToDhall` + instances)
- `Dhall.Marshal.Encode.Instances`
  Builtin instances for encoding go here

I think this would improve the hackabilty of the `Dhall` module a lot. The `Dhall` module should reexport those modules.

### PR DESCRIPTION
**Pull request by mmhat**
All decoding related code was moved to Dhall.Marshal.Decode and the
encoding related code to Dhall.Marshal.Encode respectively.

Additionally some minor documentation issues were fixed.

Fixes #1786

### CODE REVIEW

**Comment by mmhat** [comment]
Hm, Hydra fails with
```
[1 of 1] Compiling Main             ( benchmark/parser/Main.hs, dist/build/dhall-parser/dhall-parser-tmp/Main.o )
Linking dist/build/dhall-parser/dhall-parser ...
haddockPhase
Error: Incomplete haddocks
```
but my local Haddock builds look fine. What is going on here?
@Gabriel439 The last time I ran into issues concerning Hydra+Haddock your feedback resolved the issue (I cannot remember what it was exactly). Do you have any idea what went wrong this time?

General question: How do I debug problems like this? The log does not give me any clue what went wrong.

**Comment by sjakobi** [comment]
@mmhat In the case of this Hydra failure, grepping for "Incomplete haddocks" would give you a hint:

https://github.com/dhall-lang/dhall-haskell/blob/48c01709be2e3e2b465577430b15da6094e65ff8/nix/shared.nix#L123-L134

But it looks like you've already figured it out! :)

What's the motivation for creating the new namespace BTW? Do you have future plans for it?

**Comment by mmhat** [comment]
@sjakobi The motivation behind the namespaces were the following: The Dhall module in its current form has almost 3000 lines, most of them related to marshalling. Since such a huge module is kind of hard to navigate (Well, at least I had troubles the last time I contributed.) the idea was to move the decoding/encoding code to an own namespace. The goal is (was?) to end up with a clearer separation of concerns and maybe even improved compile times during development due to smaller compilation units.
As you may have noticed this PR does not (yet) implement the original module structure displayed in #1786 due to the tight coupling of the generic code and the marshalling type classes. I have to look a bit more into this if it is really worth splitting the Dhall.Marshal.{Decode,Encode} modules into smaller submodules, but I'd rather do that in a separate PR.

Regarding the Hydra+Haddock issue: Yeah, I finally remembered what caused the issue the last time I ran into this :) Since I could not find any documentation on the Haddock checks Hydra is performing I will open a PR in order to add it to our CONTRIBUTION docs after I am done with this one.

**Comment by Gabriel439** [comment]
@mmhat: Thank you for doing this! 🙂

**Pull request merged**
