### PR TITLE
dhall: Support GHC 8.8

### LINKED ISSUE #1249: GHC 8.8 tracking ticket
Tracking ticket for GHC 8.8 issues, mostly dependencies. Updated 2020-05-30:

All packages are compatible with GHC-8.8, but CI doesn't include a GHC-8.8 job yet.

### PR DESCRIPTION
**Pull request by ocharles**
Fixes #1249.

### CODE REVIEW

**Comment by ocharles** [comment]
In a sense, this PR is untested by CI. Should I also update CI to test builds on 8.8?

**Comment by sjakobi** [comment]
It seems like `turtle` still needs to relax it's upper bound on `time`:

```
≻ cabal test all -w ghc-8.8.1 --minimize-conflict-set
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: dhall-1.26.0 (user goal)
[__1] rejecting: dhall:!test (constraint from config file, command line flag,
or user target requires opposite flag selection)
[__1] trying: dhall:*test
[__2] trying: doctest-0.16.2 (dependency of dhall *test)
[__3] trying: ghc-8.8.1/installed-8.8... (dependency of doctest)
[__4] next goal: turtle (dependency of dhall *test)
[__4] rejecting: turtle-1.5.14, turtle-1.5.13, turtle-1.5.12 (conflict: ghc =>
time==1.9.3/installed-1.9..., turtle => time<1.9)
[__4] rejecting: turtle-1.5.11, turtle-1.5.10, turtle-1.5.9, turtle-1.5.8,
turtle-1.5.7, turtle-1.5.6, turtle-1.5.5, turtle-1.5.4, turtle-1.5.3,
turtle-1.5.2, turtle-1.5.1, turtle-1.5.0, turtle-1.4.6, turtle-1.4.5
(conflict: ghc => containers==0.6.2.1/installed-0.6..., turtle =>
containers>=0.5.0.0 && <0.6)
[__4] rejecting: turtle-1.4.4, turtle-1.4.3, turtle-1.4.2, turtle-1.4.1,
turtle-1.4.0, turtle-1.3.6 (conflict: ghc => time==1.9.3/installed-1.9...,
turtle => time<1.9)
[__4] rejecting: turtle-1.3.5, turtle-1.3.4, turtle-1.3.3, turtle-1.3.2,
turtle-1.3.1 (conflict: ghc => process==1.6.5.1/installed-1.6..., turtle =>
process>=1.0.1.1 && <1.5)
[__4] rejecting: turtle-1.3.0, turtle-1.2.8, turtle-1.2.7, turtle-1.2.6,
turtle-1.2.5, turtle-1.2.4, turtle-1.2.3, turtle-1.2.2, turtle-1.2.1,
turtle-1.2.0 (conflict: ghc => directory==1.3.3.2/installed-1.3..., turtle =>
directory>=1.0.7 && <1.3)
[__4] rejecting: turtle-1.1.1, turtle-1.1.0, turtle-1.0.2, turtle-1.0.1,
turtle-1.0.0 (conflict: ghc => directory==1.3.3.2/installed-1.3..., turtle =>
directory<1.3)
[__4] fail (backjumping, conflict set: dhall, ghc, turtle, dhall:test)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: ghc, doctest, base, dhall, turtle,
dhall:test
```

:+1: for CI! :)

**Comment by sjakobi** [comment]
`asn1-encoding` seems to need an update too:

```
≻ cabal build all -w ghc-8.8.1 --disable-tests
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: dhall-1.26.0 (user goal)
[__1] trying: dhall:+with-http
[__2] trying: http-client-tls-0.3.5.3 (dependency of dhall +with-http)
[__3] trying: tls-1.5.1 (dependency of http-client-tls)
[__4] trying: x509-validation-1.6.11 (dependency of tls)
[__5] trying: asn1-encoding-0.9.5 (dependency of tls)
[__6] next goal: base (dependency of dhall)
[__6] rejecting: base-4.13.0.0/installed-4.1... (conflict: asn1-encoding =>
base>=3 && <4.13)
[__6] rejecting: base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
non-upgradeable package requires installed instance)
[__6] fail (backjumping, conflict set: asn1-encoding, base, dhall)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, asn1-encoding, tls, certificate,
http-client-tls, x509-validation, dhall, dhall:with-http
Try running with --minimize-conflict-set to improve the error message.
```

**Comment by ocharles** [comment]
> It seems like turtle still needs to relax it's upper bound on time.

That has already been done, it just needs a new release.

> asn1-encoding seems to need an update too:

Strange, mine is fine... Perhaps it's jailbroken in nixpkgs.

**Comment by sjakobi** [comment]
@ocharles I think this should be merged anyway, although it doesn't fix (and shouldn't close) #1249. We can take care of CI once we can fix #1249 properly.

**Pull request merged**
