### PR TITLE
dhall-lsp-server: Normalize types before displaying them to the user

### PR DESCRIPTION
**Pull request by EggBaconAndSpam**
Previously, the type displayed when hovering over the arrow in a lambda
(or forall) binder would not always be normal:

This fix normalises types before displaying them to the user (fixes both
the type-on-hover and annotate-let behaviour):

### CODE REVIEW

**Comment by ocharles** [comment]
Hmm, this is a tricky one. Normal forms are not necessarily what you want to see - they are often significantly larger than the original expression. However, for types, because we don't have full computation in types (dependent types) that's not too likely *yet*, but it may happen in the future.

**Comment by EggBaconAndSpam** [comment]
I think normal forms are more in line with the expected behaviour. I stumbled over this in `dhall-nethack`. For example, with the old behaviour, the following type does not even fit into the tooltip window:


While the normalised type is far more informative (and shorter):


I think the essence here is that we don't have _computation_ in types, only polymorphism, and beta-reduction in the presence of polymorphism "almost always" makes the type smaller.

**Comment by EggBaconAndSpam** [comment]
@ocharles what is your opinion in this? Yay, Nay, undecided?

**Comment by ocharles** [comment]
Oh, please don't let me change what's happening here - it was merely a passing thought. If you think this is good, then stick with it. We'll find out overtime if it's not, anyway!

**Comment by EggBaconAndSpam** [comment]
No worries! You did raise an interesting point that I hadn't considered before, though. I think I'll merge and hope for the best ;)

**Comment by EggBaconAndSpam** [comment]
So how do I tell mergify that this should be merged?

**Pull request merged**
