### PR TITLE
Version 1.26.0 → 1.26.1

### PR DESCRIPTION
**Pull request by Gabriel439**
Waiting for:

* [x] https://github.com/dhall-lang/dhall-haskell/pull/1342 - Fix inferred type for record projection
* [x] https://github.com/dhall-lang/dhall-haskell/pull/1343 - Build against `Diff-0.4.*`

### CODE REVIEW

**Comment by Gabriel439** [comment]
This is a point release because I would like to get out the fix for the performance regression in #1335

**Comment by Gabriel439** [comment]
I'm going to hold off at least one day cutting the release.  I think I found a type-checking bug for record projection that might be a regression introduced by #1335

**Comment by Gabriel439** [comment]
Alright, I fixed the typechecking regression in https://github.com/dhall-lang/dhall-haskell/pull/1342

Once that is merged I will cut this release

**Comment by Gabriel439** [comment]
@jneira: It looks like AppVeyor had an issue with the API token when uploading.  See:

* https://ci.appveyor.com/project/Gabriel439/dhall-haskell/build/job/m3xar69jus9f5fv4

> Deploying using GitHub provider
> Creating "1.26.1" release for repository "dhall-lang/dhall-haskell" tag "1.26.1" commit "5b136dfa2c42ba41a57aa495091b598cc6414c9f"...
> Error creating GitHub release: Provider setting not found or it's value is empty. If secure setting is used please check that value was encrypted (or YAML was exported) while being logged under correct account.
> Parameter name: auth_token

Fortunately, it still produced the artifacts successfully, so I can still attach them to the release myself.

**Comment by jneira** [comment]
Jumm, i'm taking a look but at first glance the token seems to be right

**Comment by jneira** [comment]
@Gabriel439 I've just [tested a deploy in my repo](https://ci.appveyor.com/project/jneira/dhall-haskell/builds/27648561/job/e04y9xhig4955ny5) and it worked so maybe it was temporary :thinking:

**Comment by Gabriel439** [comment]
Hmmm, then I'll just wait and see if it happens again during the next release to see if it's a transient issue

**Pull request merged**
