### PR TITLE
Allow tasty-1.4 and tasty-silver-3.2

### PR DESCRIPTION
**Pull request by sjakobi**
Changelogs:

* http://hackage.haskell.org/package/tasty-1.4/changelog
* http://hackage.haskell.org/package/tasty-silver-3.2/changelog

Tested locally.

### CODE REVIEW

**Comment by sjakobi** [comment]
This is currently blocked on https://github.com/phile314/tasty-silver/issues/26.

**Comment by Gabriel439** [comment]
Sorry for the delay.  I missed that this was no longer blocked

**Comment by Gabriel439** [comment]
I also just created matching revisions for these packages on Hackage

**Comment by sjakobi** [comment]
> Sorry for the delay. I missed that this was no longer blocked

No worries. I could have added a comment to highlight that the PR was ready for review.

> I also just created matching revisions for these packages on Hackage

Cheers! :+1:

**Pull request merged**
