### PR TITLE
WIP: Allow and use hnix-0.8

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by sjakobi** [comment]
Travis fails due to a missing `libsodium`, which is required by [`hnix-store-core-0.2.0.0`](http://hackage.haskell.org/package/hnix-store-core-0.2.0.0) via [`saltine`](http://hackage.haskell.org/package/saltine). Looks like a bit of headache TBH.

https://github.com/haskell-nix/hnix-store/issues/65 is slightly related.

**Comment by sjakobi** [comment]
One option would be to go back to `hnix-store-core-0.1.0.0` but then we'd lose GHC-8.8 compatibility in `dhall-nix`.

**Comment by sorki** [comment]
Pulling `sodium` is a bit unfortunate since signatures are not actually used anywhere yet. Is there a way to install the package for MacOS builder or does it call for better solution like splitting `hnix-store` a bit more or `CPP`? 

At some point signatures will be needed for `hnix` as well but it could be split into multi-project too which would make for less dependency headaches for consumers who sometimes only need parser/pretty-printer which is probably the case here as well.

**Comment by sjakobi** [comment]
@sorki Thanks for chiming in! I'm installing `libsodium` with `brew` now, which seems to work so far.

As long as Hackage's docs builder doesn't provide `libsodium` we'll also to upload documentation for `dhall-nix` manually. And I expect that we'll run into other issues, here or in `hnix`.

Would it be possible to replace the `libsodium` dependency with a pure Haskell implementation, similarly to how `hnix` uses `hashing` instead of `cryptohash-*`? That would probably resolve the packaging-related problems most simply. Alternatively, maybe the `saltine` maintainer could be convinced to include the `libsodium` code in his package? That would still prevent building with GHCJS, but solve most of the other issues.

**Comment by sorki** [comment]
Looks like `Ed25519` is required so `cryptonite` would be an option (it bundles `curve25519-donna` implementation) although it was removed previously in favor of `cryptohash`.

Btw Nix can be compiled without `libsodium`
```
throw Error("Nix was not compiled with libsodium, required for signed binary cache support")
```

**Comment by sjakobi** [comment]
@sorki Yeah, even switching to a package which bundles C code would be a nice improvement! :)



> Btw Nix can be compiled without `libsodium`
> 
> ```
> throw Error("Nix was not compiled with libsodium, required for signed binary cache suppor
> ```

Do you mean the C++(?) implementation here? Interesting!

> Edit.. looks like `cryptohash` is now deprecated in favor `cryptonite` so that makes things simple.

Oh, I wasn't aware. Do you have a link?

**Comment by sorki** [comment]
> > Edit.. looks like `cryptohash` is now deprecated in favor `cryptonite` so that makes things simple.
> 
> Oh, I wasn't aware. Do you have a link?

Right in the README :) https://hackage.haskell.org/package/cryptohash

**Comment by sjakobi** [comment]
Thanks! Note BTW that this `cryptohash` package and the various `cryptohash-md5` etc. packages are under separate maintainership: My understanding is that HVR forked the `cryptohash-*` packages from Vincent Hanquez' original `cryptohash` package and apparently continues to maintain them. I'm not familiar with the details though.

**Comment by sorki** [comment]
Thanks for the clarification! I'll open an issue for `hnix-store` for further discussion about this.

**Comment by Gabriel439** [comment]
Do we still need this?  `master` is currently on `hnix-0.9`

**Comment by sjakobi** [comment]
> Do we still need this? `master` is currently on `hnix-0.9`

Oh! I somehow hadn't noticed that we actually use the new version! :)

**Pull request closed without merging**
