### PR TITLE
dhall-lsp-server: Only underline link in import

### PR DESCRIPTION
**Pull request by EggBaconAndSpam**
This restricts the clickable link part of an import to just the actual
link; previously we also underlined hash and headers if those were
present.

Now:
```
./Bool/package.dhall sha256:7ee950e7c2142be5923f76d00263e536b71d96cb9c190d7743c1679501ddeb0a
~~~~~~~~~~~~~~~~~~~~
```

Previously:
```
./Bool/package.dhall sha256:7ee950e7c2142be5923f76d00263e536b71d96cb9c190d7743c1679501ddeb0a
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### CODE REVIEW

**Comment by EggBaconAndSpam** [comment]
AppVeyor is broken again...
```
...
[00:00:25] Chocolatey installed 0/1 packages. 1 packages failed.
[00:00:25]  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
[00:00:25] 
[00:00:25] Failures
[00:00:25]  - haskell-stack - haskell-stack not installed. The package was not found with the source(s)
...
```

**Comment by sjakobi** [comment]
> AppVeyor is broken again...

Try again! https://status.chocolatey.org/ claims it's back up.

**Comment by sjakobi** [comment]
Well, it's not _quite_ up: https://chocolatey.org/packages/haskell-stack/1.9.3 says it's down. :/

**Comment by EggBaconAndSpam** [comment]
*Now* it's back!

**Pull request merged**
