### PR TITLE
Build against `profunctors-5.5.*`

### PR DESCRIPTION
**Pull request by Gabriel439**

### CODE REVIEW

**Comment by sjakobi** [comment]
We're exceeding our artifact storage space on AppVeyor again:

```
Uploading artifacts...
[1/4] bin\dhall-bash-eb1ef-x86_64-windows.zip (7,633,797 bytes)...100%
[2/4] bin\dhall-eb1ef-x86_64-windows.zip (8,330,480 bytes)...100%
Maximum allowed artifact storage size of 70000 Mb will be exceeded.
```

**Comment by Gabriel439** [comment]
@sjakobi: I've opened a support ticket here: https://help.appveyor.com/discussions/problems/24928-maximum-allowed-artifact-storage-size-of-70000-mb-will-be-exceeded

**Comment by sjakobi** [comment]
@jneira Should we try limiting the artifact upload to "more important" builds? In https://github.com/dhall-lang/dhall-haskell/pull/785 it sounds as if we're uploading build artifacts on each and every build.

**Comment by jneira** [comment]
Yeah, i think we could only upload releases

**Comment by sjakobi** [comment]
> Yeah, i think we could only upload releases

If I understand https://www.appveyor.com/docs/packaging-artifacts/ correctly, the uploading of artifacts to the artifact storage is independent of actual deployments. It seems to be automatic and not configurable.

I guess we could just comment out the [`artifact` section](https://github.com/dhall-lang/dhall-haskell/blob/8c388c79941de0b9415f6b8225b51f6b49c8a9e9/appveyor.yml#L79-L87) and uncomment it for releases, but that would be a bit awkward…

**Comment by jneira** [comment]
Not very elegant but you can simply avoid generating the zips and it will not upload them, printing a warning ([it already happens for lts-6](https://ci.appveyor.com/project/jneira/dhall-haskell/builds/26678945/job/7b21kdwd6sov1op5#L2199))

**Comment by sjakobi** [comment]
@jneira Sounds good! Can you make a patch or give me instructions? :)

**Comment by jneira** [comment]
sure! i'll cut one asap

**Pull request merged**
