### PR TITLE
Converted sample code to doctest for `RecordType`, `UnionInputType`, `RecordInputType`

### PR DESCRIPTION
**Pull request by klntsky**
`<>` is `infixr 6`, `<$>` is `infixr 4`, therefore existing example is incorrect.

It might be a good idea to reflect every piece of sample code in the tests, so that the docs will never become outdated.

I could dedicate some time to this. Should I add a test to `Dhall.Test.Tutorial` or is there a more suitable module?

### CODE REVIEW

**Comment by f-f** [comment]
I thought we had doctests running? 🤔

**Comment by quasicomputational** [comment]
`doctest` only recognises the `>>>` prefix.

**Comment by Gabriel439** [comment]
I believe this can be turned into a doctest using `ghci`'s support for multi-line expressions, like this:

```haskell
>>> data Status = Queued Natural | Result | Text | Errored Text
>>> :{
let status :: Type Status
    status = union
        $   (Queued <$> constructor "Queued" natural )
        <> ( Result  <$> constructor "Result"  strictText )
        <> ( Errored <$> constructor "Errored" strictText )
:}
```

**Comment by klntsky** [comment]
Both `injectStatus` examples were broken too (`inputUnion` call was missing).

**Comment by klntsky** [comment]
By the way, `dhall:doctest` suite [is skipped](https://github.com/dhall-lang/dhall-haskell/blob/684cbac7be0c28ce60dbe089e1f9ae6c95f6f13f/appveyor.yml#L60) in `appveyor.yml`. Is it intentional?

**Comment by Gabriel439** [comment]
@klntsky: The `doctest` omission for the `dhall` package appears to be intentional.  See:

https://github.com/dhall-lang/dhall-haskell/pull/785

> Not including dhall:doctests cause throws spurious errors due to encoding. I've not found a way to avoid them like in local (setting encoding of console to utf-8)

**Comment by Gabriel439** [comment]
@klntsky: Thank you! 🙂

**Pull request merged**
