### PR TITLE
Support `if` expressions returning a type or kind

### PR DESCRIPTION
**Pull request by Gabriel439**
… as standardized in https://github.com/dhall-lang/dhall-lang/pull/1090

### CODE REVIEW

**Comment by mheiber** [comment]
Adding a feature by removing lines :)

Screenshot 2020-10-28 at 19 05 12

**Comment by Gabriel439** [comment]
Yeah, this is my favorite kind of pull request 🙂

**Comment by mheiber** [comment]
the update to the standard https://github.com/dhall-lang/dhall-lang/pull/1090 is merged (thanks for your help)

**Comment by Gabriel439** [comment]
@mheiber: Thank you, too, for your help on this :slightly_smiling_face:

**Pull request merged**
