### PR TITLE
Optionally allow missing lists in yaml/json-to-dhall

### LINKED ISSUE #1410: [Feature Request] Tolerate missing lists and maps in yaml-to-dhall and json-to-dhall
From https://github.com/dhall-lang/dhall-kubernetes/issues/83

When I try to run `yaml-to-dhall {x : Text, y : List Text}` on this yaml:
```yaml
x: "some text"
```
It of course complains that `y` is missing. Correct type for this would be `{x : Text, y : Optional (List Text)}`, but this can become too noisy even if a few a lists are optional. This is true especially in proejcts like dhall-kubernetes where (almost?) all the lists are optional. The same applies to maps.

It would be nice to if `yaml-to-dhall` had a flag to tolerate missing lists and maps and assume empty values. It would also be the opposite of `--omitEmpty` of `dhall-to-yaml` and would allow such YAML files to re-interpreted as Dhall.

### PR DESCRIPTION
**Pull request by akshaymankar**
Fixes #1410

### CODE REVIEW

**Comment by sjakobi** [comment]
This looks great! My understanding of #1410 was that we also want the `--omissible-lists` option to replace `--omitEmpty` in `dhall-to-json` and `dhall-to-yaml`. Would you like to implement this too? Otherwise this could be done in a separate patch.

**Comment by akshaymankar** [comment]
Sure I can do that also in this PR. As this would be a breaking change, would it be better to have deprecation warnings for `omitEmpty`?

Also, should I rename `--omitNull` to `--omit-null` (omissible-null sounds weird) and `--noMaps` to `--no-maps` for consistency of case?

**Comment by sjakobi** [comment]
> As this would be a breaking change, would it be better to have deprecation warnings for `omitEmpty`?

It might be a good idea to keep `--omitEmpty` around for a bit. AFAIK we haven't used actual deprecation warnings so far, so I don't think it's necessary to add some in this case.


> Also, should I rename `--omitNull` to `--omit-null` (omissible-null sounds weird)

`--omitNull` is the default setting now, so I think we can simply get rid of it soon.

> and `--noMaps` to `--no-maps` for consistency of case?

Yes, let's get rid of camelCase in CLI options. Not sure whether we need to keep `--noMaps` around again… Thoughts @Gabriel439?

The new `--preserveNull` option should also be changed to `--preserve-null`.

**Comment by sjakobi** [comment]
Seems like the updating of the CLI options would be a well-sized change on its own, so let's maybe merge this as-is and change the options in a follow-up PR. Would that be ok for you, @akshaymankar?

**Comment by akshaymankar** [comment]
Yeah that would be ok with me, feel free to merge :)

**Pull request merged**
