### PR TITLE
Add `{json,yaml}-to-dhall` support for using `toMap`

### PR DESCRIPTION
**Pull request by Gabriel439**
Fixes https://github.com/dhall-lang/dhall-haskell/issues/1744

... and also fix `{json,yaml}-to-dhall` to use `toMap`, too

### CODE REVIEW

**Comment by sjakobi** [comment]
I believe we'll need to check whether the `mapKey`s are sorted in ascending order. Otherwise the resulting `toMap`-expression  will not be equivalent. In brief:

```dhall
[ { mapKey = "a", mapValue = 1 }, { mapKey = "b", mapValue = 2 } ] === toMap { a = 1, b = 2 }
```

but

```dhall
[ { mapKey = "b", mapValue = 2 }, { mapKey = "a", mapValue = 1 } ] =/= toMap { a = 1, b = 2 }
```

I wonder how that check will affect the `{json,yaml}-to-dhall` output though.

**Comment by Gabriel439** [comment]
@sjakobi: Another option might be to not perform this rewrite in `dhall lint` at all and instead do the rewrite only in `{json,yaml}-to-dhall`, which would have fixed the original request anyway

**Comment by sjakobi** [comment]
Sounds good to me!

**Comment by sjakobi** [comment]
BTW, when you change a PR in way that the current PR title and description don't fit anymore, I think it would be safer to update those too. I think we've already had a few changelog entries that were actually false, just because we changed course in a PR.

**Pull request merged**
