### PR TITLE
Remove Optional/fold and Optional/build

### PR DESCRIPTION
**Pull request by sjakobi**
…as standardized in https://github.com/dhall-lang/dhall-lang/pull/1014.

~~Note that the test suite doesn't completely pass yet since we haven't updated the code to comply with https://github.com/dhall-lang/dhall-lang/pull/980 yet.~~

### CODE REVIEW

**Comment by sjakobi** [comment]
I don't understand why the type-inference failure tests that I added fail in this way:

```
  type-inference tests
    discover
      ./dhall-lang/tests/type-inference/failure/unit/RemovedBuiltinOptionalBuild:                                              FAIL
        tests/Dhall/Test/TypeInference.hs:109:
        ./dhall-lang/tests/type-inference/failure/unit/RemovedBuiltinOptionalBuild should have parsed
      ./dhall-lang/tests/type-inference/failure/unit/RemovedBuiltinOptionalFold:                                               FAIL
        tests/Dhall/Test/TypeInference.hs:109:
        ./dhall-lang/tests/type-inference/failure/unit/RemovedBuiltinOptionalFold should have parsed
```

Indeed `Optional/fold` and `Optional/build` fail to parse(!) in the REPL too:

```
⊢ Optional/fold

Error: Invalid input

(input):1:9:
  |
1 | Optional/fold
  |         ^
unexpected '/'
expecting ->, :, end of input, keyword, operator, or whitespace

⊢ Optional/build

Error: Invalid input

(input):1:9:
  |
1 | Optional/build
  |         ^
unexpected '/'
expecting ->, :, end of input, keyword, operator, or whitespace
```

I assume I must have made a mistake somewhere in the  parser…

**Comment by sjakobi** [comment]
Ah, I had forgotten to update the `reservedIdentifiers` list! :)

**Comment by sjakobi** [comment]
Got a hopefully spurious AppVeyor error:

```
Build started
git clone -q https://github.com/dhall-lang/dhall-haskell.git C:\projects\dhall-haskell
fatal: unable to access 'https://github.com/dhall-lang/dhall-haskell.git/': Could not resolve host: github.com
Command exited with code 128
```

Retrying…

**Comment by sjakobi** [comment]
I had forgotten to update the `.dhall.bin` files in `dhall/benchmark/examples`

**Comment by Gabriel439** [comment]
@sjakobi: `hydra` is failing with this error:

```
Building source dist for dhall-1.32.0...
dhall-lang/tests/import/cache/dhall/1220efc43103e49b56c5bf089db8e0365bbfc455b8a2f0dc6ee5727a3586f85969fd: getPermissions:getFileStatus: does not exist (No such file or directory)
builder for '/nix/store/ky647iz7avzm9l5xddd9a1zixc00q2dy-dhall-sdist.drv' failed with exit code 
```

https://hydra.dhall-lang.org/jobset/dhall-haskell/1802#tabs-errors

I think this just requires updating the path in the `Extra-Source-Files` section

**Comment by sjakobi** [comment]
Many thanks for the hint @Gabriel439. Turns out we never included the cache file for the poisoned cache test: https://github.com/dhall-lang/dhall-lang/blob/549470527dcc0ee59253708c6ac23c0cee455093/tests/import/cache/dhall/1220618f785ce8f3930a9144398f576f0a992544b51212bc9108c31b4e670dc6ed21

D'oh!

**Comment by Gabriel439** [comment]
@sjakobi: You're welcome! 🙂

**Pull request merged**
