### PR TITLE
Use atomic-write for inplace file modifications

### LINKED ISSUE #498: dhall format --inplace should force the resulting string before writing it
I just lost a Dhall file because I ran `dhall-format` on it and hit a bug. This meant the file just contained a huge list of `(` - presumably an infinite loop somewhere - causing me to lose the contents of the file (yet to reach source control). In an ideal world it wouldn't go wrong, but we don't live in an ideal world. I'll take the extra memory usage of buffering the contents first and witnessing the formatting terminate before writing the file.

This is on Dhall 1.15. I can't report a bug as to what went wrong with formatting because I don't have the input anymore :laughing:

### PR DESCRIPTION
**Pull request by sjakobi**
Fixes #498.

### CODE REVIEW

**Comment by sjakobi** [comment]
Does this look like a good approach @Gabriel439? In that case there are more spots that I could change similarly.

**Comment by sjakobi** [comment]
I've addressed `lint` and  `freeze` too. There are a bunch of commands that have an `--output` option. Should we use `atomic-write` there too?

**Comment by Gabriel439** [comment]
@sjakobi: Yeah, I think it should be fine to do this for `--output`, too

**Comment by sjakobi** [comment]
I have adjusted only `dhall --output` for now, since it seems somewhat plausible to use that for an inplace file modification, where the source could be lost.

In `{json,yaml}-to-dhall` and `dhall-to-{json,yaml,yaml-ng}` that seems less likely since the input and the output have different formats, so I've skipped that for now…

**Comment by Gabriel439** [comment]
@sjakobi: Alright, that sounds reasonable

**Pull request merged**
