### PR TITLE
add tomland dependency and bump stackage snapshot

### PR DESCRIPTION
**Pull request by ear7h**
The stackage snapshot version was updated to get the an update version of
tomland. The old snapshot had version 1.1.0.1 and the latest snapshot
has version 1.3.2.0. Version [1.3.0.0](https://github.com/kowainik/tomland/blob/main/CHANGELOG.md#1300--may-19-2020) had a relatively large change to the
package organization as well as bug fixes.

### CODE REVIEW

**Comment by sjakobi** [comment]
Looks pretty good. I can take a closer look once CI passes.

**Comment by Gabriel439** [comment]
@ear7h: You will need to update the `tomland` dependency for Nix by install `cabal2nix` and doing:

```bash
$ cabal2nix cabal://tomland > ./nix/packages/tomland.nix
```

... and you will probably also want to decrease the lower bound on the `text` dependency, too

**Comment by ear7h** [comment]
@Gabriel439 should I do that instead of changing the stackage version? or along side it? Because it looks the CI failed to find the version I specified

**Comment by Gabriel439** [comment]
@ear7h: You would need to do both, because we build each project using both `stack` and Nix, and each tool has a different way of pinning dependencies

**Comment by Gabriel439** [comment]
It looks like you will also need to pin `validation-selective` in `stack.yaml`

**Review by sjakobi — APPROVED** [review]

**Pull request merged**
