### PR TITLE
First release of dhall-docs

### LINKED ISSUE #1900: dhall-docs release
Do we need to follow a procedure to release dhall-docs?

From my POV, it looks like we need to:

* Add `dhall-docs` to release.sh
* Update `.travis.yml` for GitHub releases

### PR DESCRIPTION
**Pull request by german1608**
Closes #1900

### CODE REVIEW

**Comment by german1608** [comment]
Not quite sure if I updated `appveyor` correctly, I'm not so familiar with its format.

**Comment by german1608** [comment]
@Gabriel439: will be necessary to create a git tag? I don't know if you're the only one that can do so.

I think that travis-ci, for instance, only publishes the artifacts if the commit is tagged.

**Comment by Gabriel439** [comment]
@german1608: I will include it as part of the next monthly release.  Currently we only create `git` tags for `dhall` releases

**Comment by german1608** [comment]
@Gabriel439: Ok.

I was planning to submit an announcement tomorrow at discourse about that dhall-docs can start to be actually used, but I worried about how could they actually download an artifact.

Guess that their only option is to build from source.

**Comment by Gabriel439** [comment]
@german1608: If you want, we can still release `dhall-docs` early.  There just wouldn't be a `git` tag associated with it

**Comment by german1608** [comment]
> @german1608: If you want, we can still release `dhall-docs` early. There just wouldn't be a `git` tag associated with it

how so?

**Comment by german1608** [comment]
> @german1608: If you want, we can still release `dhall-docs` early. There just wouldn't be a `git` tag associated with it

It's ok for me to not have the `git` tag, though.

**Comment by german1608** [comment]
Tests fails on appveyor, but I don't have windows to check the reason, and tasty fails when trying to show the diff.

I'll remove `dhall-docs` from there, but should be good for someone else with Windows to checkout the difference.

**Comment by german1608** [comment]
Tests fails on appveyor, but I don't have windows to check the reason, and tasty fails when trying to show the diff.

I'll remove `dhall-docs` from there, but should be good for someone else with Windows to checkout the difference.

**Comment by sjakobi** [comment]
> Tests fails on appveyor, but I don't have windows to check the reason, and tasty fails when trying to show the diff.

Could you make a bug report?

It would be good if at least some of the tests were re-enabled soon.

**Comment by sjakobi** [comment]
> It would be good if at least some of the tests were re-enabled soon.

Maybe record this as a task on the issue tracker…

**Pull request merged**
