### PR TITLE
constructors === id

### LINKED ISSUE #635: deprecate constructors
Making an issue to mirror https://github.com/dhall-lang/dhall-lang/issues/244

I'm currently trying to tackle it right now and I'm running into a bit of a wall with understanding what I need to change. @Gabriel439 is there a workflow of how to update a change in the core language that you work by? For example, change `Parser` -> `TypeChecker` -> `Normalizer`. Or do you have some jumping off points for me to look at?

Thanks!

### PR DESCRIPTION
**Pull request by FintanH**
Fixes #635

Stage 2 of: https://github.com/dhall-lang/dhall-lang/issues/244

Implements the semantics merged here: https://github.com/dhall-lang/dhall-lang/pull/256

The idea is that `constructors` is equivalent to the identity function so it returns the `Union` as-is. This means `constructors` does not create a record of functions to `UnionLit`s but rather utilises the new `Union` access syntax.

### CODE REVIEW

**Comment by Gabriel439** [comment]
@FintanH: Alright, feel free to merge this now.  You will need to re-freeze `./dhall/tests/import/success/issu553B.dhall` to reserve the merge conflict

**Comment by Gabriel439** [comment]
Actually, hold off on merging this for just a few days.  I'm going to cut a new minor release with the fix to `dhall lint` in https://github.com/dhall-lang/dhall-haskell/pull/703 since that's a pretty nasty bug and the fix should be published soon

**Comment by FintanH** [comment]
Updated the branch :ok_hand: I had to add `dotgen` to `stack.yaml` to get things to compiling

**Comment by basile-henry** [comment]
@FintanH Sorry about that, I should have checked that we could still build with `stack` before I merged https://github.com/dhall-lang/dhall-haskell/pull/698

**Comment by FintanH** [comment]
No problem @basile-henry, that PR is so cool! The dhall-to-cabal graph :heart_eyes:

**Pull request merged**
