### PR TITLE
dhall-lsp-server: Improve type-on-hover behaviour over binders

### PR DESCRIPTION
**Pull request by EggBaconAndSpam**
Dhall's parser does not generate `Src` annotations for the names in
binders, which means that it's not quite as straight-forward to check
whether the user meant to hover over it and see its type as one would
hope. As a result, the current "naive" implementation sometimes behaves
slightly unintuitively and returns the type of the entire expression,
rather than the type of the bound variable. E.g.:

This change recovers the `Src` information describing the bound variable
names and handles those cases in a way that should be more in line with
the expectations of the user:

### CODE REVIEW

**Comment by sjakobi** [comment]
I'm closing this one to see whether that gets Mergify unstuck. Will reopen (if I can?!) right again.

**Comment by sjakobi** [comment]
Argh! Nope. :(

**Comment by Gabriel439** [comment]
@sjakobi: I can fix this to remove the stale status soon (using GitHub's API).  Alternatively, I can bypass the checks to merge if necessary as administrator

**Comment by EggBaconAndSpam** [comment]
I'm fixing the merge conflicts right now.

**Pull request merged**
