### PR TITLE
RFC: Dhall.Map: Change fromList to be left-biased in the values

### LINKED ISSUE #1052: Dhall.Map.fromList doesn't distribute over (<>)
Aside from the use of `(<|>)`, the documentation for `Dhall.Map.fromList` seems to state a distributive law:

https://github.com/dhall-lang/dhall-haskell/blob/92bdd56a3426bb912aadc0ab9b8a8effe0ec6714/dhall/src/Dhall/Map.hs#L135-L152

That property doesn't hold though, as `Data.Map.union` is left-biased, while `Data.Map.fromList` is right-biased:

```
λ> x = [((),True)]
λ> y = [((),False)]
λ> Dhall.Map.fromList (x <> y)
fromList [((),False)]
λ> Dhall.Map.fromList x <> Dhall.Map.fromList y
fromList [((),True)]
```

Is this an important property that we'd actually like to have? Or can we simply fix the documentation?

### PR DESCRIPTION
**Pull request by sjakobi**
Given

    fromList [(2,True),(1,True),(1,False),(2,False)]

previously the resulting Dhall.Map was:

    fromList [(2,False),(1,False)]

Now we get

    fromList [(2,True),(1,True)]

So both the order of keys and the values are determined by each first
unique key. Duplicate keys don't change the result at all.

The property

    fromList (x <|> y) = fromList x <> fromList y

now holds.

Closes #1052.

Also add some doctest properties.

### CODE REVIEW

**Comment by sjakobi** [comment]
The downside of this change is that if the input list has any duplicate keys, e.g. due to a programming error, you're unlikely to detect them.

Maybe we really want something like `fromUniqueList` that throws an error when there's a duplicate key.

**Comment by sjakobi** [comment]
Another alternative:

Update `fromList`'s documentation to reflect its current behaviour, and be done with it.

**Comment by sjakobi** [comment]
@f-f if you have a bit of time, could you maybe review this too?

**Comment by f-f** [comment]
@sjakobi thanks for the ping! This looks fine, but I'm not sure about the implications, e.g. do you have a more specific usecase in mind? (other than support that property)

**Comment by sjakobi** [comment]
Thanks the review @f-f! :)

> This looks fine, but I'm not sure about the implications, e.g. do you have a more specific usecase in mind? (other than support that property)

Performance-wise, it slows things down very slightly.

AFAIK the change in the resulting map cannot be observed in in this repo as we only apply `fromList` on inputs with distinct keys. Anyone else might be in for a surprise!

I really don't like this change. I'll make a PR to fix `fromList`'s documentation instead.

**Pull request closed without merging**
