### PR TITLE
Fix performance regression for `with` expressions

### PR DESCRIPTION
**Pull request by Gabriel439**
Fixes: https://github.com/dhall-lang/dhall-haskell/issues/2105

### CODE REVIEW

**Comment by ggilmore** [comment]
Thank you! Would it be possible to roll this into a patch release, or should we wait for `1.38.0`?

**Comment by Gabriel439** [comment]
@ggilmore: I can cut an early 1.37.1 release to get this fix out

**Review by sjakobi — APPROVED** [review]

**Comment by ggilmore** [comment]
Awesome thank you! Also I don't know if this is the appropriate place to ask this, but is there a test that can be added to the suite that would catch this in the future? It might be tricky if the only indicator of an issue is the length of the execution time though.

**Comment by Gabriel439** [comment]
@ggilmore: Probably not.  Anything that would causes tests to fail would be problematic when run on different machines (e.g. as part of Nixpkgs CI, for example)

**Pull request merged**
