### PR TITLE
Add cost centres in decodeExpressionInternal

### PR DESCRIPTION
**Pull request by sjakobi**
…to aid profiling.

Context: #1804.

### CODE REVIEW

**Comment by sjakobi** [comment]
Hydra reports:

```
      ./dhall-lang/tests/type-inference/success/CacheImportsCanonicalize:                                                      FAIL (5.02s)
        tests/Dhall/Test/TypeInference.hs:73:

        Error: Remote host not found

        URL: https://test.dhall-lang.org/random-string
```

Should I simply try again?

**Comment by sjakobi** [comment]
@Gabriel439 How do I convince Hydra to give my patch another chance? Or does the error indicate some underlying problem that needs to be addressed?

**Comment by Gabriel439** [comment]
@sjakobi: If you have a GPG key I can create a Hydra account for you so that you can restart things on your own.  In the interim, I'll go ahead and restart the build myself.  I'd also be fine with disabling that test.

**Comment by Gabriel439** [comment]
@sjakobi: Also, I generally don't recommend checking `SCC` annotations into version control.  The reason why is that if you're not interested in profiling that specific code at a given time they will distort the profile to make that code look more expensive compared to the rest of the code base.  This is because `SCC` annotations will interfere with optimizations / inlining.

**Comment by sjakobi** [comment]
I don't currently have GPG set up, but you make a good point that these cost centers might distort other profiling results, so I'm fine with not merging this. I'll keep the branch though for future use.

Regarding the test failure – is that an error after which we might want to [retry](https://github.com/dhall-lang/dhall-haskell/issues/1794#issuecomment-628820114) the request? Otherwise I also wouldn't mind disabling it.

**Comment by Gabriel439** [comment]
@sjakobi: Rather than retry at the test level, we should consider if we should have the interpreter automatically retry all imports as discussed in https://github.com/dhall-lang/dhall-haskell/issues/1794

**Comment by sjakobi** [comment]
Yeah, that's what I meant. :)

**Comment by winitzki** [comment]
CI / standard tests no longer depend on test.dhall-lang.org

**Pull request closed without merging**
