### PR TITLE
WIP: Integrate new tests

### PR DESCRIPTION
**Pull request by sjakobi**
...from https://github.com/dhall-lang/dhall-lang/pull/933.

TODO:

* [x] [`RemoteChainEnv`](https://github.com/dhall-lang/dhall-lang/pull/933/files#diff-2ef92c6d2580511ead81ec4321022f76)
* [ ] [`Hash`](https://github.com/dhall-lang/dhall-lang/pull/933/files#diff-d991df79a15a50fecc42942792cb3e4d)

### CODE REVIEW

**Comment by sjakobi** [comment]
I don't understand why the `import/success/unit/asLocation/HashA.dhall` test succeeds when I run the entire `tasty` testsuite, but fails when I run just it:

```
$ cabal test dhall:tasty -w ghc-8.6.5 --test-show-details=streaming --test-options "-p HashA"
...
Dhall Tests
  import tests
    discover
      ./dhall-lang/tests/import/success/unit/SimpleHashA.dhall:      OK
      ./dhall-lang/tests/import/success/unit/asLocation/HashA.dhall: FAIL
        Exception: 
        ↳ ./dhall-lang/tests/import/success/unit/asLocation/some/import.dhall sha256:efc43103e49b56c5bf089db8e0365bbfc455b8a2f0dc6ee5727a3586f85969fd as Location
        
        Error: Import integrity check failed
        
        Expected hash:
        
        ↳ efc43103e49b56c5bf089db8e0365bbfc455b8a2f0dc6ee5727a3586f85969fd
        
        Actual hash:
        
        ↳ efe6b86554985c1864806b97b4113d262ccc97decd81df6e90af0566553f493d
        
        
        6│ ./some/import.dhall sha256:efc43103e49b56c5bf089db8e0365bbfc455b8a2f0dc6ee5727a3586f85969fd as Location
        
        6:1
      ./dhall-lang/tests/import/success/nestedHashA.dhall:           OK

1 out of 3 tests failed (0.01s)
Test suite tasty: FAIL
Test suite logged to:
/home/simon/src/dhall-haskell/dist-newstyle/build/x86_64-linux/ghc-8.6.5/dhall-1.30.0/t/tasty/test/dhall-1.30.0-tasty.log
0 of 1 test suites (0 of 1 test cases) passed.
cabal: Tests failed for test:tasty from dhall-1.30.0.
```

If running _all_ the tests would hide failures in individual test cases, that would be very worrying.

**Comment by Nadrieril** [comment]
I'm surprised that you would get this error: if your test harness is setup according to https://github.com/dhall-lang/dhall-lang/blob/master/tests/README.md#running-import-tests, that hash should be present in the cache. I'm guessing that this setup is only done when you run all tests ?

**Comment by Gabriel439** [comment]
@sjakobi: While testing https://github.com/dhall-lang/dhall-haskell/pull/1710 the `HashA.dhall` test failed for me even when running the entire test suite

**Comment by sjakobi** [comment]
I wonder whether there's some kind of underlying caching issue, possibly involving the semi-semantic cache.

#1710 has made better progress with the tests though, so I'll close this and try to address the failing `Hash` test separately.

**Pull request closed without merging**
