### PR TITLE
Use path-0.8

### PR DESCRIPTION
**Pull request by sjakobi**
See http://hackage.haskell.org/package/path-0.8.0/changelog.

### CODE REVIEW

**Comment by sjakobi** [comment]
FYI, I'm using https://packdeps.haskellers.com/feed?needle=dhall to get notifications about outdated dependencies.

(Since I don't use an RSS reader, I use https://blogtrottr.com/ to get email notifications)

**Comment by Gabriel439** [comment]
@sjakobi: Usually I found out about these via Stackage.  I get pinged on issues like these: https://github.com/commercialhaskell/stackage/issues/5558

**Comment by sjakobi** [comment]
> @sjakobi: Usually I found out about these via Stackage. I get pinged on issues like these: [commercialhaskell/stackage#5558](https://github.com/commercialhaskell/stackage/issues/5558)

`dhall-docs` isn't on Stackage yet – should we add it?

**Comment by Gabriel439** [comment]
@sjakobi: Yeah, I think we should add `dhall-docs` to Stackage and Brew after we cut the 1.0.0 release

**Pull request merged**
