### PR TITLE
Allow optparse-applicative 0.16

### PR DESCRIPTION
**Pull request by sjakobi**
Changelog:
http://hackage.haskell.org/package/optparse-applicative-0.16.0.0/changelog

Stackage: https://github.com/commercialhaskell/stackage/issues/5597

### CODE REVIEW

**Comment by sjakobi** [comment]
I haven't been able to get a clean build with the new version yet – `optparse-generic` apparently needs an update first.

**Comment by Gabriel439** [comment]
@sjakobi: `optparse-generic-1.4.3` is now out, which will build against `optparse-applicative-0.16.0.0`

**Comment by sjakobi** [comment]
Thanks @Gabriel439! The build succeeded now.

**Comment by sjakobi** [comment]
I've made matching Hackage revisions for `dhall`, `dhall-json` and `dhall-yaml`. For `dhall-docs` and `dhall-nixpkgs` I didn't have the necessary permissions.

**Comment by HuwCampbell** [comment]
It looks like `hnix` might need a bump as well for `dhall-nix` to work.

**Comment by Gabriel439** [comment]
@sjakobi: I added you as a maintainer to the remaining packages and also updated the remaining revisions

**Comment by sjakobi** [comment]
> It looks like `hnix` might need a bump as well for `dhall-nix` to work.

Done: https://github.com/haskell-nix/hnix/pull/697

**Pull request merged**
