### PR TITLE
Handle empty lists without annotations as parse errors

### PR DESCRIPTION
**Pull request by sjakobi**
Here are a few samples of the parse errors:

```
⊢ []

Error: Invalid input

(input):2:1:
  |
2 | <empty line>
  | ^
Empty list literal without annotation

⊢ ([]) : T

Error: Invalid input

(input):1:4:
  |
1 | ([]) : T
  |    ^
Empty list literal without annotation

⊢ { c = [] }

Error: Invalid input

(input):1:10:
  |
1 | { c = [] }
  |          ^
Empty list literal without annotation

```

### CODE REVIEW

**Comment by sjakobi** [comment]
I'm still getting a doctest failure that I'm not sure how to fix:

```
/home/simon/src/dhall-haskell/dhall/src/Dhall/Tutorial.hs:452: failure in expression `input auto "[]" :: IO (Vector Natural)'
expected: "*** Exception:"
          "...Error...: Invalid input"
          "..."
          "(input):1:3:"
          "  |"
          "1 | []"
          "  |   ^"
          "Empty list literal without annotation"
 but got: "*** Exception: "
          "\ESC[1;31mError\ESC[0m: Invalid input"
          ""
          "(input):1:3:"
          "  |"
          "1 | []"
          "  |   ^"
          "Empty list literal without annotation"
          ""
```

Is there a good way to change the example so we don't get the escape codes?

**Comment by Gabriel439** [comment]
@sjakobi: The issue isn't the escape codes since those are handled by the `...` in the sample `doctest` output.  The problem is that (for some reason) parse errors have an additional space after the `*** Exception: ` and the original type error did not.

**Comment by sjakobi** [comment]
> @sjakobi: The issue isn't the escape codes since those are handled by the `...` in the sample `doctest` output. The problem is that (for some reason) parse errors have an additional space after the `*** Exception: ` and the original type error did not.

Oh! Interestingly, fixing that alone isn't sufficient. Apparently `doctest` can handle that trailing whitespace just fine.

The real problem was a missing line at the end of the output, which I fixed with 

```diff
--- a/dhall/src/Dhall/Tutorial.hs
+++ b/dhall/src/Dhall/Tutorial.hs
@@ -458,6 +458,7 @@ import Dhall
 -- 1 | []
 --   |   ^
 -- Empty list literal without annotation
+-- ...
 --
 -- Also, list elements must all have the same type.  You will get an error if
 -- you try to store elements of different types in a list:
```

**Comment by sjakobi** [comment]
I was wondering whether we need to change anything about the `MissingListType` type error. It's probably still reachable in some way though, so I'll leave it there for now.

**Pull request merged**
