### PR TITLE
Add Benchmarking

### PR DESCRIPTION
**Pull request by FintanH**
This PR add benchmarking to the `dhall-lang` repo.

The benchmarking at the moment is directly related to #108 (parsing performance). Thus it tests `exprFromText` on multiple samples. One of the samples is the expression mentioned in #108. The other samples come from the `Prelude` directory itself. 

It can take a few minutes so it might be an idea to use only a subset of `Prelude`.

### CODE REVIEW

**Comment by FintanH** [comment]
Just some more information. I ran with `--profile` and an obvious cost centre popped its head:

```
COST CENTRE                 MODULE                            SRC                                                    %time %alloc

text                        Dhall.Parser                      src/Dhall/Parser.hs:131:3-95                            23.9    6.2
splitAt.loop.len            Data.Text.Lazy                    Data/Text/Lazy.hs:1255:20-50                             9.2    0.0
primitiveExpression         Dhall.Parser                      src/Dhall/Parser.hs:(1236,1)-(1440,16)                   6.2    6.8
iterN.loop                  Data.Text                         Data/Text.hs:(1088,9)-(1091,29)                          4.4    0.0
noted                       Dhall.Parser                      src/Dhall/Parser.hs:(144,1)-(148,45)                     3.8    8.3
getPosition                 Text.Megaparsec                   Text/Megaparsec.hs:1434:1-51                             2.9    5.1
compare                     Text.Megaparsec.Pos               Text/Megaparsec/Pos.hs:127:31-33                         2.2    1.6
>>=                         Data.Vector.Fusion.Util           Data/Vector/Fusion/Util.hs:36:3-18                       2.1    4.4
takeN_                      Text.Megaparsec.Stream            Text/Megaparsec/Stream.hs:(249,3)-(252,54)               2.0    1.7
<?>                         Dhall.Parser                      src/Dhall/Parser.hs:108:3-31                             1.9    2.5
splitAt.loop                Data.Text.Lazy                    Data/Text/Lazy.hs:(1248,9)-(1255,50)                     1.9    7.2
equal                       Data.Text.Lazy                    Data/Text/Lazy.hs:(301,1)-(312,31)                       1.8    0.0
reserved                    Dhall.Parser                      src/Dhall/Parser.hs:528:1-56                             1.6    2.2
mplus                       Text.Megaparsec                   Text/Megaparsec.hs:446:3-15                              1.6    2.7
<*>                         Text.Megaparsec                   Text/Megaparsec.hs:352:3-16                              1.4    2.1
fromString                  Dhall.Parser                      src/Dhall/Parser.hs:103:5-77                             1.3    1.7
splitAt.loop.(...)          Data.Text.Lazy                    Data/Text/Lazy.hs:1251:32-70                             1.3    1.7
makeOperatorExpression      Dhall.Parser                      src/Dhall/Parser.hs:(1164,1)-(1168,40)                   1.2    1.9
splitAt                     Data.Text                         Data/Text.hs:(1268,1)-(1272,63)                          1.1    8.0
doubleLiteral               Dhall.Parser                      src/Dhall/Parser.hs:(745,1)-(749,42)                     1.1    1.4
whitespaceChunk             Dhall.Parser                      src/Dhall/Parser.hs:(218,1)-(226,52)                     1.1    1.9
simpleLabel                 Dhall.Parser                      src/Dhall/Parser.hs:(265,1)-(275,76)                     1.0    1.2
getTokensProcessed          Text.Megaparsec                   Text/Megaparsec.hs:1486:1-60                             0.8    1.7
blockCommentChunk.character Dhall.Parser                      src/Dhall/Parser.hs:(186,5)-(188,78)                     0.6    1.3
fmap                        Data.Vector.Fusion.Stream.Monadic Data/Vector/Fusion/Stream/Monadic.hs:(133,3)-(135,20)    0.5    1.1
basicUnsafeIndexM           Data.Vector.Primitive             Data/Vector/Primitive.hs:222:3-75                        0.5    1.1
```

`text` is defined as:
```haskell
text = fmap Data.Text.Lazy.toStrict . Text.Megaparsec.Char.string . Data.Text.Lazy.fromStrict
```

I wonder if the `Text` conversions there are a hot spot.

**Comment by FintanH** [comment]
Running benchmarks on Formation code there's also a hotspot:
```
splitAt.loop.len       Data.Text.Lazy         Data/Text/Lazy.hs:1255:20-50             82.0    0.7
```

This gives us non-terminating tests for more complicated cases. Looking through the benchmarking further we see:
```
tokens                                                                                            Dhall.Parser                            src/Dhall/Parser.hs:89:9-45                                   158074          0    0.0    0.1     1.4    0.5
            takeN_                                                                                           Text.Megaparsec.Stream                  Text/Megaparsec/Stream.hs:(249,3)-(252,54)                    158075     125206    0.0    0.0     1.3    0.3
             splitAt                                                                                         Data.Text.Lazy                          Data/Text/Lazy.hs:(1247,1)-(1255,50)                          158076          0    0.0    0.0     1.3    0.3
              splitAt.loop                                                                                   Data.Text.Lazy                          Data/Text/Lazy.hs:(1248,9)-(1255,50)                          158077     125204    0.0    0.1     1.3    0.3
               splitAt.loop.len                                                                              Data.Text.Lazy                          Data/Text/Lazy.hs:1255:20-50                                  158078     125204    1.3    0.0     1.3    0.0

```

**Comment by quasicomputational** [comment]
You probably also want to add the `.dhall` file to `extra-source-files`.

**Comment by Gabriel439** [comment]
I will merge this soon.  I just need to update the Nix code so that CI exercises the benchmark suite

**Comment by quasicomputational** [comment]
Which version of GHC are you running these benchmarks on? I ask because I'm seeing different results for 8.2.1 and 8.4.2 in some other benchmarks I'm doing: `splitAt` is quite prominent in 8.2, but it's nowhere to be seen in 8.4 (and the whole thing runs faster, too).

**Comment by Gabriel439** [comment]
Note that CI currently uses GHC 8.2.2, but I can always change that to any version (or multiple versions)

**Comment by Gabriel439** [comment]
I have a pull request against your pull request to add Nix support here: https://github.com/FintanH/dhall-haskell/pull/1

**Comment by FintanH** [comment]
So I tried to run `stack bench --profile` with the resolver `nightly-2018-05-30` which includes 8.4 but it hangs on the benchmarking code. This only happens with the `--profile` flag. Not sure what's happening yet.

**Pull request merged**
