### PR TITLE
dhall-lsp-server: Update to haskell-lsp 0.19

### PR DESCRIPTION
**Pull request by EggBaconAndSpam**
As suggested by @sjakobi in #1622.

### CODE REVIEW

**Comment by sjakobi** [comment]
@EggBaconAndSpam I believe you'll need to update the versions in the `stack.yaml` too.

**Comment by EggBaconAndSpam** [comment]
> @EggBaconAndSpam I believe you'll need to update the versions in the `stack.yaml` too.

Yup I missed that one, thanks @sjakobi!

**Comment by Gabriel439** [comment]
@EggBaconAndSpam: Looks like the tests need to be updated for `haskell-lsp-server-0.19`, too

**Comment by EggBaconAndSpam** [comment]
Damn :smile: I'll fix it on Saturday!

**Comment by EggBaconAndSpam** [comment]
Looks like we need a newer parser-combinators than the stack lts provides.

**Comment by Gabriel439** [comment]
@EggBaconAndSpam: Thank you! 🙂

**Pull request merged**
