### PR TITLE
Fix merging of sort-level record types.

### LINKED ISSUE #890: Can’t merge two record sorts.
```dhall
{ a : Kind } ⩓ { b : Kind }
```
currently fails with “Error: Record type mismatch”, which it should be a valid merge.

### PR DESCRIPTION
**Pull request by sellout**
Fixes #890.

### CODE REVIEW

**Comment by sellout** [comment]
The dhall-lang submodule will need to be updated once dhall-lang/dhall-lang#486 is merged.

**Comment by Gabriel439** [comment]
https://github.com/dhall-lang/dhall-lang/pull/486 is merged so if you update this branch then tests should now pass

**Comment by sellout** [comment]
Looks like the `largeExpression` parser test now fails.

/cc @singpolyma, since they made the latest change to that test.

**Comment by f-f** [comment]
@sellout yeah it looks like there's something with that test: now both dhall-haskell master and dhall-clj master produce the same parse for it, and the result differs from the one in dhall-lang. 
However https://github.com/dhall-lang/dhall-lang/pull/488 will change it again, so we could wait for that (though it will require changes in dhall-haskell)

**Comment by singpolyma** [comment]
I've merged https://github.com/dhall-lang/dhall-lang/pull/488 now -- not sure how the failure happened before since I produce that `.dhallb` file previously with `dhall encode` -- now the version in master is produced with `dhall-ruby` and should be correct for the changes in 488

**Comment by sellout** [comment]
Should this wait on #903, then?

**Comment by Gabriel439** [comment]
@sellout: Yeah, if you update to the latest `master` then you should pick up all relevant changes

**Comment by Gabriel439** [comment]
Thanks for fixing this! 🙂

**Pull request merged**
