### PR TITLE
Fix alpha normalization (#929)

### PR DESCRIPTION
**Pull request by AndrasKovacs**
Trivial typo fix.

### CODE REVIEW

**Comment by Gabriel439** [comment]
I'll also cut a new release once this and all of the union-related issues are fixed

**Comment by ocharles** [comment]
May I suggest turning off -fno-warn-unused?

**Comment by jneira** [comment]
Also, have you considered setup a little bit slower release process with beta or/and alpha releases (for one week max?)? Not sure if it could help to avoid quick fix minor releases after major ones

**Comment by AndrasKovacs** [comment]
@ocharles agree, I intended but forgot to remove that flag

**Comment by Gabriel439** [comment]
@jneira: I would prefer to increase the test coverage or improve our use of the compiler/type-checker rather than slow down the release process.  For example: as @ocharles  suggested, this would have been caught by removing the `-fno-warn-unused` flag

The reason I prefer not to slow down the release process or to have stabilization periods is because in my experience it leads to less frequent releases and higher coordination costs.  It also outsources the burden of quality to our users.

**Pull request merged**
