### PR TITLE
Mergify: Delete head branch after merge

### PR DESCRIPTION
**Pull request by sjakobi**
Docs: https://doc.mergify.io/examples.html#deleting-merged-branch

### CODE REVIEW

**Comment by sjakobi** [comment]
It's strange that Mergify hasn't merged this one yet. Maybe because I'm changing its configuration?!

I'll merge this one by hand so we'll see how things go with the next PRs.

**Comment by Gabriel439** [comment]
@sjakobi: Yes, if you click through the mergify status it says it won't auto-merge a pull request that changes the mergify configuration

**Comment by sjakobi** [comment]
It's a bit strange that the Mergify rule added here seems to cause #1067's "checks status" to remain yellow / in progress forever.

In general, I wouldn't mind to revert this change if it seems to cause problems.

**Comment by Gabriel439** [comment]
@sjakobi: Let's revert for now until we understand the correct usage

**Pull request merged**
