### PR TITLE
Update Stack setup to LTS 19 (GHC 9.0.2)

### PR DESCRIPTION
**Pull request by mmhat**
Greetings from ZuriHac!

### CODE REVIEW

**Comment by Gabriella439** [comment]
hmmm the test failures seem a bit surprising; it's not clear how they relate to the change

**Comment by mmhat** [comment]
> hmmm the test failures seem a bit surprising; it's not clear how they relate to the change

I suspect that the doctest version (0.18.2; previously: 0.17) causes the trouble. I had a quick look at the changelog and the source code diff but it is not clear to me how to fix that. Someone at ZuriHac suggested to switch to cabal-docspec; I'll try that.

**Comment by mmhat** [comment]
Regarding the doctest issue: The upstream bug report is https://github.com/sol/doctest/issues/327.

I tried using cabal-docspec (did not push the code to a branch yet) and while the output is much better it requires to change some tests. I am not sure if that is worth the effort if we we can get the tests running with doctest.

**Comment by mmhat** [comment]
I am closing this in favor of https://github.com/dhall-lang/dhall-haskell/pull/2531. Supporting GHC 9.0 is IMHO not that important if we have a working setup for 9.2.

**Pull request closed without merging**
