### PR TITLE
Introduce normalizeWithM for monadic normalization

### PR DESCRIPTION
**Pull request by alexbiehl**
See the discussion in https://github.com/dhall-lang/dhall-lang/issues/133.

### CODE REVIEW

**Comment by alexbiehl** [comment]
- [ ] This needs a big comment saying  that this might violate assumptions

**Comment by Gabriel439** [comment]
Don't forget to export `NormalizerM` and `normalizeWithM` from the module

**Comment by Gabriel439** [comment]
I'll close this for now since from offline discussions it sounded like you could do this using the existing API by post-processing the abstract syntax tree to monadically normalize uninterpreted free variables

**Comment by Gabriel439** [comment]
@ocharles: Yeah, it seems reasonable to proceed with this change

**Comment by ocharles** [comment]
Ok, I think this is good for review.

**Pull request closed without merging**
