### PR TITLE
WIP: implement toJSON keyword

### PR DESCRIPTION
**Pull request by KAction**
Hello. I am trying to implement toJSON (#336) keyword. I managed to
add keyword to parser (that was easy), added constructor ToJSON into
Expr, created Expr corresponding to Prelude.JSON.Type and returned it
unconditionally in TypeCheck.hs. Yes, I know that I have to check that
it actually possible to convert argument to JSON, but it is WIP.

Next step is handle ToJSON constructor in Eval.hs. I started with very
trivial case when argument for toJSON keyword is integer (currently
"eval" is partial and can crash). Here is example input I tested on:

````
(toJSON +42) Natural
{
  array = \(x: List Natural) -> 1,
  bool = \(x: Bool) -> 2,
  integer = \(x: Integer) -> 3,
  null = 4,
  object = \(x: List { mapKey : Text, mapValue : Natural }) -> 5,
  double = \(x: Double) -> 6,
  string = \(x: Text) -> 7
}
````

It evaluates to following expression:

````
  ( forall (t : Type) ->
    forall  ( json
            : { array : List t -> t
              , bool : Bool -> t
              , double : Double -> t
              , integer : Integer -> t
              , null : t
              , string : Text -> t
              , object : List { mapKey : Text, mapValue : t } -> t
              }
            ) ->
      json.integer +42
  )
    Natural
    { array = \(x : List Natural) -> 1
    , bool = \(x : Bool) -> 2
    , double = \(x : Double) -> 6
    , integer = \(x : Integer) -> 3
    , null = 4
    , object = \(x : List { mapKey : Text, mapValue : Natural }) -> 5
    , string = \(x : Text) -> 7
    }
: Natural
````

which is correct, but should be simplified further. And here I am stuck,
I can't understand how to simplify all this to `3 : Natural`.

May I ask for some advice and guidance?

### CODE REVIEW

**Comment by MonoidMusician** [comment]
It looks like you mixed Pis and Lambdas up in your definition of `json`. You need the latter, not the former, since you are constructing a value of the JSON type (not declaring the JSON type).

**Comment by sjakobi** [comment]
Wow. It's nice to see some progress here! :)

FYI, the link to the `toJSON` issue should point to https://github.com/dhall-lang/dhall-lang/issues/336, not https://github.com/dhall-lang/dhall-haskell/pull/336, which is just an old PR.

**Comment by Gabriel439** [comment]
@KAction: Note that before we can merge this we need to make a matching change to the standard.  I'll be more free to help with that starting next week

**Comment by Gabriel439** [comment]
Actually, I've been more busy than I expected.  It might be a while before I get to this, so I apologize.  There are a few performance improvements that I need to work on, first

**Pull request closed without merging**
