### PR TITLE
WIP: Remove Eta Yaml FFI stuff

### PR DESCRIPTION
**Pull request by patrickmn**
Etlas build seems broken (not because of these changes). @jneira, any idea?

```
% etlas build dhall-json
Resolving dependencies...
etlas: Could not resolve dependencies:
next goal: aeson (dependency of dhall-1.26.1)
rejecting: aeson-1.4.0.0, aeson-1.2.4.0, aeson-1.2.3.0, aeson-1.2.2.0
(conflict: th-abstraction==0.3.1.0, aeson => th-abstraction>=0.2.2 && <0.3)
trying: aeson-1.2.1.0
trying: dhall-nix-1.1.8 (user goal)
next goal: hnix (dependency of dhall-nix-1.1.8)
rejecting: hnix-0.6.1 (conflict: aeson==1.2.1.0, hnix => aeson>=1.4.2 && <1.5)
rejecting: hnix-0.6.0, hnix-0.5.2, hnix-0.5.1, hnix-0.5.0, hnix-0.4.0,
hnix-0.3.4, hnix-0.3.3, hnix-0.3.2, hnix-0.2.1, hnix-0.2.0 (conflict:
dhall-nix => hnix>=0.6.1 && <0.7)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: dhall-nix, hnix, dhall,
template-haskell, binary, eta-meta

% etlas build dhall-json --allow-newer
Resolving dependencies...
etlas: Could not resolve dependencies:
trying: aeson-1.4.0.0 (dependency of dhall-1.26.1)
trying: dhall-nix-1.1.8 (user goal)
next goal: hnix (dependency of dhall-nix-1.1.8)
rejecting: hnix-0.6.1 (conflict: aeson==1.4.0.0, hnix => aeson>=1.4.2)
rejecting: hnix-0.6.0, hnix-0.5.2, hnix-0.5.1, hnix-0.5.0, hnix-0.4.0,
hnix-0.3.4, hnix-0.3.3, hnix-0.3.2, hnix-0.2.1, hnix-0.2.0 (conflict:
dhall-nix => hnix>=0.6.1)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: dhall-nix, hnix, dhall,
template-haskell, binary, eta-meta
```

### CODE REVIEW

**Comment by jneira** [comment]
Mmm, etlas (like cabal) tries to resolve the dependencies of all local packages, including `dhall-nix`. It turns out that in windows it is already unbuildable and my etlas builds ignore it. So i guess the quick one would be mark `dhall-nix`unbuildable for eta replacing in `dhall-nix.cabal`:
```
if os(windows)
        Buildable: False
```
with
```
if os(windows) || impl(eta)
        Buildable: False
```

**Comment by patrickmn** [comment]
Yep, that did it!

**Comment by patrickmn** [comment]
I think @rahulmutt mentioned changes to etlas were comparatively easy -- this seems like one that's gonna cause a lot of issues.

eta-hackage patch also works!

Since the FFI-based Eta build works for now, let's hold off on merging until everything builds?

**Comment by jneira** [comment]
@patrickmn yeah, merge it when ci finishes

**Comment by patrickmn** [comment]
Ah right, forgot that gpl is off by default. Will do.

**Pull request merged**
