### PR TITLE
Dhall.Eval.eqMapsBy: Compare map sizes before contents

### PR DESCRIPTION
**Pull request by sjakobi**
Data.Map.size is O(1), so we expose that via Dhall.Map.

### CODE REVIEW

**Comment by sjakobi** [comment]
Maybe `eqMapsBy` should even be moved into `Dhall.Map`?!

**Comment by Gabriel439** [comment]
Also, it's fine if we move the logic into `Dhall.Map` like you suggested

**Comment by sjakobi** [comment]
> Maybe `eqMapsBy` should even be moved into `Dhall.Map`?!

Ah, I'll hold off until we need the same function in a different module.

**Comment by sjakobi** [comment]
The Mergify check doesn't even show up now. Maybe because the config is different on this branch?!

I'll update the branch to see if that fixes it.

**Pull request merged**
