### PR TITLE
GHCJS support for Dhall

### PR DESCRIPTION
**Pull request by Gabriel439**
This adds a GHCJS build for Dhall so that:

* We can build a `try.dhall-lang.org` to try Dhall in the
  browser until the PureScript implementation comes online
* We can document how to build `dhall` using GHCJS
* We can verify that new changes to `dhall` or its dependencies
  don't break GHCJS support
* CI can build and cache GHCJS-related dependencies

### CODE REVIEW

**Comment by Profpatsch** [comment]
I experimented with this in the past, if you want to take a look: https://github.com/Profpatsch/dhall-js

**Comment by masaeedu** [comment]
@Gabriel439 Is `try.dhall-lang.org` no longer a thing?

**Comment by Gabriel439** [comment]
@masaeedu: It's now https://dhall-lang.org

**Comment by Profpatsch** [comment]
Congrats on the new website!

**Comment by Gabriel439** [comment]
Thank you 🙂

**Pull request merged**
