### PR TITLE
Don't allow mixed-style records for using expressions

### PR DESCRIPTION
**Pull request by TimWSpence**
Previously it was valid to write

import XXX using [ { header = "foo", mapValue = "bar" } ]
or
import XXX using [ { mapKey = "foo", value = "bar" } ]

whereas only

import XXX using [ { header = "foo", value = "bar" } ]
or
import XXX using [ { mapKey = "foo", mapValue = "bar" } ]

should be allowed

### CODE REVIEW

**Comment by TimWSpence** [comment]
@Gabriel439 as we discussed in https://discourse.dhall-lang.org/t/valid-expressions-for-using-headers/205/3

However, I checked and the mixed style is actually rejected by the type checker. I think this code more reflects the intention but it's probably not strictly necessary due to the type checker doing the work so not offended if you don't want to bother merging!

**Comment by TimWSpence** [comment]
Also, I wasn't sure if you wanted me to add any failure tests to dhall-lang for it?

**Comment by TimWSpence** [comment]
Thanks @Gabriel439 !!! It's a bank holiday here so I'll probably be occupied entertaining the family but will look into the tests and merge early next week

**Comment by Gabriel439** [comment]
@TimWSpence: Actually, it looks like the mixed-style was actually correctly forbidden before, albeit at a downstream step here:

https://github.com/dhall-lang/dhall-haskell/blob/b54787ecbd4a4e2ef3516344da9655aace327566/dhall/src/Dhall/Import.hs#L950-L961

I ran into this when trying to write a regression test and found that the Haskell implementation was actually rejecting it properly:

```
$ dhall <<< 'https://example.com using [ { mapKey = "X-Foo", value = "Foo" } ] as Text'
Error: Expression doesn't match annotation

…
{ - mapValue : …
, + value : …
, …
}

1│                           [ { mapKey = "X-Foo", value = "Foo" } ] : List { mapKey : Text, mapValue : Text }

(stdin):1:27

1│ https://example.com using [ { mapKey = "X-Foo", value = "Foo" } ] as Text

(stdin):1:1
```

However, I still think this is a good change regardless, so I'll go ahead and merge this in without the regression test.

**Comment by TimWSpence** [comment]
👍 thanks @Gabriel439 !

**Comment by Gabriel439** [comment]
@TimWSpence: You're welcome! 🙂

**Pull request merged**
