### PR TITLE
Use normalized filepaths in dhall testsuite

### PR DESCRIPTION
**Pull request by mmhat**
Missing filepath normalization caused some failures in #2591 ; See https://github.com/dhall-lang/dhall-haskell/actions/runs/9338722607/job/25702207276?pr=2591 for an example.

Other changes:
- Require `turtle >=1.6` in all packages.
- Use `hnix-0.17` in Stack configurations.
- Also add `mkParsec` method to `MonadParsec` instance for `megaparsec >=9.4`.

### CODE REVIEW

**Comment by winitzki** [comment]
A hydra failure might be cached; I had to make a dummy change (renamed a dummy variable) to make hydra forget the failure in a previously cached build.

**Comment by mmhat** [comment]
@winitzki Unfortunately that didn't work.
Hydra is out of disk space; See https://hydra.dhall-lang.org/build/115335/nixlog/1 and https://hydra.dhall-lang.org/build/115308/nixlog/1 .

I don't have access to that machine; @Gabriella439 can you have a look?

**Comment by winitzki** [comment]
"Hydra can't really be killed. You cut one head off, two more will grow."

**Comment by mmhat** [comment]
> "Hydra can't really be killed. You cut one head off, two more will grow."

@winitzki :smile: It seems you are right; It's working again.

**Pull request merged**
