### PR TITLE
Fix benchmarks, run them in CI

### LINKED ISSUE #1028: Broken benchmarks
```
≻ stack bench dhall:bench:dhall-parser
Cabal file warning in/home/simon/src/dhall-haskell/dhall-json/dhall-json.cabal@71:9: Unknown field: "maven-depends"
Cabal file warning in/home/simon/src/dhall-haskell/dhall-json/dhall-json.cabal@76:9: Unknown field: "java-sources"
dhall> benchmarks
Running 1 benchmarks...
Benchmark dhall-parser: RUNNING...
dhall-parser: Prelude: changeWorkingDirectory: does not exist (No such file or directory)
Benchmark dhall-parser: ERROR

--  While building package dhall-1.24.0 using:
      /home/simon/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.4 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 bench dhall-parser
    Process exited with code: ExitFailure 1
```

```
≻ stack bench dhall:bench:deep-nested-large-record
Cabal file warning in/home/simon/src/dhall-haskell/dhall-json/dhall-json.cabal@71:9: Unknown field: "maven-depends"
Cabal file warning in/home/simon/src/dhall-haskell/dhall-json/dhall-json.cabal@76:9: Unknown field: "java-sources"
dhall> benchmarks
Running 1 benchmarks...
Benchmark deep-nested-large-record: RUNNING...
deep-nested-large-record: 
↳ ./benchmark/deep-nested-large-record/prelude.dhall

Error: Invalid input

/home/simon/src/dhall-haskell/dhall/benchmark/deep-nested-large-record/prelude.dhall:2:23:
  |
2 |   { Big = constructors ./BigEnum.dhall
  |                       ^
expecting expression or whitespace

Benchmark deep-nested-large-record: ERROR

--  While building package dhall-1.24.0 using:
      /home/simon/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.4 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 bench deep-nested-large-record
    Process exited with code: ExitFailure 1
```
```
≻ stack bench dhall:bench:dhall-command
Cabal file warning in/home/simon/src/dhall-haskell/dhall-json/dhall-json.cabal@71:9: Unknown field: "maven-depends"
Cabal file warning in/home/simon/src/dhall-haskell/dhall-json/dhall-json.cabal@76:9: Unknown field: "java-sources"
dhall> benchmarks
Running 1 benchmarks...
Benchmark dhall-command: RUNNING...

Error: Invalid input

(stdin):1:1:
  |
1 | <empty line>
  | ^
unexpected end of input
expecting expression or whitespace

Benchmark dhall-command: ERROR

--  While building package dhall-1.24.0 using:
      /home/simon/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.4 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 bench dhall-command
    Process exited with code: ExitFailure 1
```

### PR DESCRIPTION
**Pull request by sjakobi**
This removes the `dhall-command` benchmark, added as a profiling tool in #608. Instead I added profiling instructions to the main README.

Fixes #1028.

### CODE REVIEW

**Comment by sjakobi** [comment]
CI is currently green due to https://github.com/dhall-lang/dhall-haskell/issues/1034.

**Comment by Gabriel439** [comment]
@sjakobi: This pull request against your branch adds benchmarks to Nix CI: https://github.com/sjakobi/dhall-haskell/pull/1

**Comment by sjakobi** [comment]
@Gabriel439 Is it the `coverage-dhall` job that is supposed to run the benchmarks now? I can't find any mention of benchmarks in its logs.

I'm unfamiliar with Hydra though so maybe I'm navigating it in the wrong way.

**Comment by Gabriel439** [comment]
@sjakobi: It looks like actually running the benchmarks is not supported by the current revision of Nixpkgs that we use.  All that it currently does is ensure that benchmark-related dependencies are available, but if we upgrade to a newer revision then it will actually run the benchmarks.

I'm currently trying to create a separate pull request to upgrade Nixpkgs

**Comment by ocharles** [comment]
I'm not sure running them in CI is a great idea, it's a very non-deterministic environment. If there are other builds going on, you're going to be starved for CPU and get very different results.

**Comment by sjakobi** [comment]
@ocharles. Yeah, this is only about ensuring that the benchmarks continue to work.

**Comment by Gabriel439** [comment]
@ocharles: I'm assuming we cap the time for the benchmarks before merging this, as suggested in https://github.com/dhall-lang/dhall-haskell/issues/1028#issuecomment-506151531

**Comment by Gabriel439** [comment]
@sjakobi: I wasn't able to upgrade Nixpkgs, mainly due to this issue: https://github.com/nh2/static-haskell-nix/issues/29

We'll have to live with the inability for Nix to run benchmarks in CI for now.  Maybe only run them in AppVeyor

**Comment by sjakobi** [comment]
> @sjakobi: I wasn't able to upgrade Nixpkgs, mainly due to this issue: [nh2/static-haskell-nix#29](https://github.com/nh2/static-haskell-nix/issues/29)

Thanks for looking into this @Gabriel439! :)

> We'll have to live with the inability for Nix to run benchmarks in CI for now. Maybe only run them in AppVeyor

That seems good enough.

Should we include the changes to `nix/shared.nix` anyway?

**Comment by sjakobi** [comment]
Ah, so the `dhall-command` actually hangs on AppVeyor. I'm removing it, and have added profiling instructions in the README instead.

**Pull request merged**
